import classNames from 'classnames';

import { ToIntentColorProps, toIntentColorVariables } from './toIntentColor';

export const toHoverIntentColor = ({ prefix, intent = 'primary', intentWeight = 500 }: ToIntentColorProps) => {
  // Option
  const {
    isTextPrefix,
    isBGPrefix,
    isBorderPrefix,
    isOutlinePrefix,
    isRingPrefix,
    isRingOffsetPrefix,
    isFillPrefix,
    is50Weight,
    is100Weight,
    is200Weight,
    is300Weight,
    is400Weight,
    is500Weight,
    is600Weight,
    is700Weight,
    is800Weight,
    is900Weight,
    isLightIntent,
    isDarkIntent,
    isNeutralIntent,
    isPrimaryIntent,
    isInfoIntent,
    isSuccessIntent,
    isWarningIntent,
    isDangerIntent,
  } = toIntentColorVariables({
    prefix,
    intent,
    intentWeight,
  });

  return classNames({
    /**
     * @name text
     */
    // light
    'hover:text-light-50': isTextPrefix && is50Weight && isLightIntent,
    'hover:text-light-100': isTextPrefix && is100Weight && isLightIntent,
    'hover:text-light-200': isTextPrefix && is200Weight && isLightIntent,
    'hover:text-light-300': isTextPrefix && is300Weight && isLightIntent,
    'hover:text-light-400': isTextPrefix && is400Weight && isLightIntent,
    'hover:text-light-500': isTextPrefix && is500Weight && isLightIntent,
    'hover:text-light-600': isTextPrefix && is600Weight && isLightIntent,
    'hover:text-light-700': isTextPrefix && is700Weight && isLightIntent,
    'hover:text-light-800': isTextPrefix && is800Weight && isLightIntent,
    'hover:text-light-900': isTextPrefix && is900Weight && isLightIntent,
    // dark
    'hover:text-dark-50': isTextPrefix && is50Weight && isDarkIntent,
    'hover:text-dark-100': isTextPrefix && is100Weight && isDarkIntent,
    'hover:text-dark-200': isTextPrefix && is200Weight && isDarkIntent,
    'hover:text-dark-300': isTextPrefix && is300Weight && isDarkIntent,
    'hover:text-dark-400': isTextPrefix && is400Weight && isDarkIntent,
    'hover:text-dark-500': isTextPrefix && is500Weight && isDarkIntent,
    'hover:text-dark-600': isTextPrefix && is600Weight && isDarkIntent,
    'hover:text-dark-700': isTextPrefix && is700Weight && isDarkIntent,
    'hover:text-dark-800': isTextPrefix && is800Weight && isDarkIntent,
    'hover:text-dark-900': isTextPrefix && is900Weight && isDarkIntent,
    // neutral
    'hover:text-neutral-50': isTextPrefix && is50Weight && isNeutralIntent,
    'hover:text-neutral-100': isTextPrefix && is100Weight && isNeutralIntent,
    'hover:text-neutral-200': isTextPrefix && is200Weight && isNeutralIntent,
    'hover:text-neutral-300': isTextPrefix && is300Weight && isNeutralIntent,
    'hover:text-neutral-400': isTextPrefix && is400Weight && isNeutralIntent,
    'hover:text-neutral-500': isTextPrefix && is500Weight && isNeutralIntent,
    'hover:text-neutral-600': isTextPrefix && is600Weight && isNeutralIntent,
    'hover:text-neutral-700': isTextPrefix && is700Weight && isNeutralIntent,
    'hover:text-neutral-800': isTextPrefix && is800Weight && isNeutralIntent,
    'hover:text-neutral-900': isTextPrefix && is900Weight && isNeutralIntent,
    // primary
    'hover:text-primary-50': isTextPrefix && is50Weight && isPrimaryIntent,
    'hover:text-primary-100': isTextPrefix && is100Weight && isPrimaryIntent,
    'hover:text-primary-200': isTextPrefix && is200Weight && isPrimaryIntent,
    'hover:text-primary-300': isTextPrefix && is300Weight && isPrimaryIntent,
    'hover:text-primary-400': isTextPrefix && is400Weight && isPrimaryIntent,
    'hover:text-primary-500': isTextPrefix && is500Weight && isPrimaryIntent,
    'hover:text-primary-600': isTextPrefix && is600Weight && isPrimaryIntent,
    'hover:text-primary-700': isTextPrefix && is700Weight && isPrimaryIntent,
    'hover:text-primary-800': isTextPrefix && is800Weight && isPrimaryIntent,
    'hover:text-primary-900': isTextPrefix && is900Weight && isPrimaryIntent,
    // info
    'hover:text-info-50': isTextPrefix && is50Weight && isInfoIntent,
    'hover:text-info-100': isTextPrefix && is100Weight && isInfoIntent,
    'hover:text-info-200': isTextPrefix && is200Weight && isInfoIntent,
    'hover:text-info-300': isTextPrefix && is300Weight && isInfoIntent,
    'hover:text-info-400': isTextPrefix && is400Weight && isInfoIntent,
    'hover:text-info-500': isTextPrefix && is500Weight && isInfoIntent,
    'hover:text-info-600': isTextPrefix && is600Weight && isInfoIntent,
    'hover:text-info-700': isTextPrefix && is700Weight && isInfoIntent,
    'hover:text-info-800': isTextPrefix && is800Weight && isInfoIntent,
    'hover:text-info-900': isTextPrefix && is900Weight && isInfoIntent,
    // success
    'hover:text-success-50': isTextPrefix && is50Weight && isSuccessIntent,
    'hover:text-success-100': isTextPrefix && is100Weight && isSuccessIntent,
    'hover:text-success-200': isTextPrefix && is200Weight && isSuccessIntent,
    'hover:text-success-300': isTextPrefix && is300Weight && isSuccessIntent,
    'hover:text-success-400': isTextPrefix && is400Weight && isSuccessIntent,
    'hover:text-success-500': isTextPrefix && is500Weight && isSuccessIntent,
    'hover:text-success-600': isTextPrefix && is600Weight && isSuccessIntent,
    'hover:text-success-700': isTextPrefix && is700Weight && isSuccessIntent,
    'hover:text-success-800': isTextPrefix && is800Weight && isSuccessIntent,
    'hover:text-success-900': isTextPrefix && is900Weight && isSuccessIntent,
    // warning
    'hover:text-warning-50': isTextPrefix && is50Weight && isWarningIntent,
    'hover:text-warning-100': isTextPrefix && is100Weight && isWarningIntent,
    'hover:text-warning-200': isTextPrefix && is200Weight && isWarningIntent,
    'hover:text-warning-300': isTextPrefix && is300Weight && isWarningIntent,
    'hover:text-warning-400': isTextPrefix && is400Weight && isWarningIntent,
    'hover:text-warning-500': isTextPrefix && is500Weight && isWarningIntent,
    'hover:text-warning-600': isTextPrefix && is600Weight && isWarningIntent,
    'hover:text-warning-700': isTextPrefix && is700Weight && isWarningIntent,
    'hover:text-warning-800': isTextPrefix && is800Weight && isWarningIntent,
    'hover:text-warning-900': isTextPrefix && is900Weight && isWarningIntent,
    // danger
    'hover:text-danger-50': isTextPrefix && is50Weight && isDangerIntent,
    'hover:text-danger-100': isTextPrefix && is100Weight && isDangerIntent,
    'hover:text-danger-200': isTextPrefix && is200Weight && isDangerIntent,
    'hover:text-danger-300': isTextPrefix && is300Weight && isDangerIntent,
    'hover:text-danger-400': isTextPrefix && is400Weight && isDangerIntent,
    'hover:text-danger-500': isTextPrefix && is500Weight && isDangerIntent,
    'hover:text-danger-600': isTextPrefix && is600Weight && isDangerIntent,
    'hover:text-danger-700': isTextPrefix && is700Weight && isDangerIntent,
    'hover:text-danger-800': isTextPrefix && is800Weight && isDangerIntent,
    'hover:text-danger-900': isTextPrefix && is900Weight && isDangerIntent,
    /**
     * @name bg
     */
    // light
    'hover:bg-light-50': isBGPrefix && is50Weight && isLightIntent,
    'hover:bg-light-100': isBGPrefix && is100Weight && isLightIntent,
    'hover:bg-light-200': isBGPrefix && is200Weight && isLightIntent,
    'hover:bg-light-300': isBGPrefix && is300Weight && isLightIntent,
    'hover:bg-light-400': isBGPrefix && is400Weight && isLightIntent,
    'hover:bg-light-500': isBGPrefix && is500Weight && isLightIntent,
    'hover:bg-light-600': isBGPrefix && is600Weight && isLightIntent,
    'hover:bg-light-700': isBGPrefix && is700Weight && isLightIntent,
    'hover:bg-light-800': isBGPrefix && is800Weight && isLightIntent,
    'hover:bg-light-900': isBGPrefix && is900Weight && isLightIntent,
    // dark
    'hover:bg-dark-50': isBGPrefix && is50Weight && isDarkIntent,
    'hover:bg-dark-100': isBGPrefix && is100Weight && isDarkIntent,
    'hover:bg-dark-200': isBGPrefix && is200Weight && isDarkIntent,
    'hover:bg-dark-300': isBGPrefix && is300Weight && isDarkIntent,
    'hover:bg-dark-400': isBGPrefix && is400Weight && isDarkIntent,
    'hover:bg-dark-500': isBGPrefix && is500Weight && isDarkIntent,
    'hover:bg-dark-600': isBGPrefix && is600Weight && isDarkIntent,
    'hover:bg-dark-700': isBGPrefix && is700Weight && isDarkIntent,
    'hover:bg-dark-800': isBGPrefix && is800Weight && isDarkIntent,
    'hover:bg-dark-900': isBGPrefix && is900Weight && isDarkIntent,
    // neutral
    'hover:bg-neutral-50': isBGPrefix && is50Weight && isNeutralIntent,
    'hover:bg-neutral-100': isBGPrefix && is100Weight && isNeutralIntent,
    'hover:bg-neutral-200': isBGPrefix && is200Weight && isNeutralIntent,
    'hover:bg-neutral-300': isBGPrefix && is300Weight && isNeutralIntent,
    'hover:bg-neutral-400': isBGPrefix && is400Weight && isNeutralIntent,
    'hover:bg-neutral-500': isBGPrefix && is500Weight && isNeutralIntent,
    'hover:bg-neutral-600': isBGPrefix && is600Weight && isNeutralIntent,
    'hover:bg-neutral-700': isBGPrefix && is700Weight && isNeutralIntent,
    'hover:bg-neutral-800': isBGPrefix && is800Weight && isNeutralIntent,
    'hover:bg-neutral-900': isBGPrefix && is900Weight && isNeutralIntent,
    // primary
    'hover:bg-primary-50': isBGPrefix && is50Weight && isPrimaryIntent,
    'hover:bg-primary-100': isBGPrefix && is100Weight && isPrimaryIntent,
    'hover:bg-primary-200': isBGPrefix && is200Weight && isPrimaryIntent,
    'hover:bg-primary-300': isBGPrefix && is300Weight && isPrimaryIntent,
    'hover:bg-primary-400': isBGPrefix && is400Weight && isPrimaryIntent,
    'hover:bg-primary-500': isBGPrefix && is500Weight && isPrimaryIntent,
    'hover:bg-primary-600': isBGPrefix && is600Weight && isPrimaryIntent,
    'hover:bg-primary-700': isBGPrefix && is700Weight && isPrimaryIntent,
    'hover:bg-primary-800': isBGPrefix && is800Weight && isPrimaryIntent,
    'hover:bg-primary-900': isBGPrefix && is900Weight && isPrimaryIntent,
    // info
    'hover:bg-info-50': isBGPrefix && is50Weight && isInfoIntent,
    'hover:bg-info-100': isBGPrefix && is100Weight && isInfoIntent,
    'hover:bg-info-200': isBGPrefix && is200Weight && isInfoIntent,
    'hover:bg-info-300': isBGPrefix && is300Weight && isInfoIntent,
    'hover:bg-info-400': isBGPrefix && is400Weight && isInfoIntent,
    'hover:bg-info-500': isBGPrefix && is500Weight && isInfoIntent,
    'hover:bg-info-600': isBGPrefix && is600Weight && isInfoIntent,
    'hover:bg-info-700': isBGPrefix && is700Weight && isInfoIntent,
    'hover:bg-info-800': isBGPrefix && is800Weight && isInfoIntent,
    'hover:bg-info-900': isBGPrefix && is900Weight && isInfoIntent,
    // success
    'hover:bg-success-50': isBGPrefix && is50Weight && isSuccessIntent,
    'hover:bg-success-100': isBGPrefix && is100Weight && isSuccessIntent,
    'hover:bg-success-200': isBGPrefix && is200Weight && isSuccessIntent,
    'hover:bg-success-300': isBGPrefix && is300Weight && isSuccessIntent,
    'hover:bg-success-400': isBGPrefix && is400Weight && isSuccessIntent,
    'hover:bg-success-500': isBGPrefix && is500Weight && isSuccessIntent,
    'hover:bg-success-600': isBGPrefix && is600Weight && isSuccessIntent,
    'hover:bg-success-700': isBGPrefix && is700Weight && isSuccessIntent,
    'hover:bg-success-800': isBGPrefix && is800Weight && isSuccessIntent,
    'hover:bg-success-900': isBGPrefix && is900Weight && isSuccessIntent,
    // warning
    'hover:bg-warning-50': isBGPrefix && is50Weight && isWarningIntent,
    'hover:bg-warning-100': isBGPrefix && is100Weight && isWarningIntent,
    'hover:bg-warning-200': isBGPrefix && is200Weight && isWarningIntent,
    'hover:bg-warning-300': isBGPrefix && is300Weight && isWarningIntent,
    'hover:bg-warning-400': isBGPrefix && is400Weight && isWarningIntent,
    'hover:bg-warning-500': isBGPrefix && is500Weight && isWarningIntent,
    'hover:bg-warning-600': isBGPrefix && is600Weight && isWarningIntent,
    'hover:bg-warning-700': isBGPrefix && is700Weight && isWarningIntent,
    'hover:bg-warning-800': isBGPrefix && is800Weight && isWarningIntent,
    'hover:bg-warning-900': isBGPrefix && is900Weight && isWarningIntent,
    // danger
    'hover:bg-danger-50': isBGPrefix && is50Weight && isDangerIntent,
    'hover:bg-danger-100': isBGPrefix && is100Weight && isDangerIntent,
    'hover:bg-danger-200': isBGPrefix && is200Weight && isDangerIntent,
    'hover:bg-danger-300': isBGPrefix && is300Weight && isDangerIntent,
    'hover:bg-danger-400': isBGPrefix && is400Weight && isDangerIntent,
    'hover:bg-danger-500': isBGPrefix && is500Weight && isDangerIntent,
    'hover:bg-danger-600': isBGPrefix && is600Weight && isDangerIntent,
    'hover:bg-danger-700': isBGPrefix && is700Weight && isDangerIntent,
    'hover:bg-danger-800': isBGPrefix && is800Weight && isDangerIntent,
    'hover:bg-danger-900': isBGPrefix && is900Weight && isDangerIntent,
    /**
     * @name border
     */
    // light
    'hover:border-light-50': isBorderPrefix && is50Weight && isLightIntent,
    'hover:border-light-100': isBorderPrefix && is100Weight && isLightIntent,
    'hover:border-light-200': isBorderPrefix && is200Weight && isLightIntent,
    'hover:border-light-300': isBorderPrefix && is300Weight && isLightIntent,
    'hover:border-light-400': isBorderPrefix && is400Weight && isLightIntent,
    'hover:border-light-500': isBorderPrefix && is500Weight && isLightIntent,
    'hover:border-light-600': isBorderPrefix && is600Weight && isLightIntent,
    'hover:border-light-700': isBorderPrefix && is700Weight && isLightIntent,
    'hover:border-light-800': isBorderPrefix && is800Weight && isLightIntent,
    'hover:border-light-900': isBorderPrefix && is900Weight && isLightIntent,
    // dark
    'hover:border-dark-50': isBorderPrefix && is50Weight && isDarkIntent,
    'hover:border-dark-100': isBorderPrefix && is100Weight && isDarkIntent,
    'hover:border-dark-200': isBorderPrefix && is200Weight && isDarkIntent,
    'hover:border-dark-300': isBorderPrefix && is300Weight && isDarkIntent,
    'hover:border-dark-400': isBorderPrefix && is400Weight && isDarkIntent,
    'hover:border-dark-500': isBorderPrefix && is500Weight && isDarkIntent,
    'hover:border-dark-600': isBorderPrefix && is600Weight && isDarkIntent,
    'hover:border-dark-700': isBorderPrefix && is700Weight && isDarkIntent,
    'hover:border-dark-800': isBorderPrefix && is800Weight && isDarkIntent,
    'hover:border-dark-900': isBorderPrefix && is900Weight && isDarkIntent,
    // neutral
    'hover:border-neutral-50': isBorderPrefix && is50Weight && isNeutralIntent,
    'hover:border-neutral-100': isBorderPrefix && is100Weight && isNeutralIntent,
    'hover:border-neutral-200': isBorderPrefix && is200Weight && isNeutralIntent,
    'hover:border-neutral-300': isBorderPrefix && is300Weight && isNeutralIntent,
    'hover:border-neutral-400': isBorderPrefix && is400Weight && isNeutralIntent,
    'hover:border-neutral-500': isBorderPrefix && is500Weight && isNeutralIntent,
    'hover:border-neutral-600': isBorderPrefix && is600Weight && isNeutralIntent,
    'hover:border-neutral-700': isBorderPrefix && is700Weight && isNeutralIntent,
    'hover:border-neutral-800': isBorderPrefix && is800Weight && isNeutralIntent,
    'hover:border-neutral-900': isBorderPrefix && is900Weight && isNeutralIntent,
    // primary
    'hover:border-primary-50': isBorderPrefix && is50Weight && isPrimaryIntent,
    'hover:border-primary-100': isBorderPrefix && is100Weight && isPrimaryIntent,
    'hover:border-primary-200': isBorderPrefix && is200Weight && isPrimaryIntent,
    'hover:border-primary-300': isBorderPrefix && is300Weight && isPrimaryIntent,
    'hover:border-primary-400': isBorderPrefix && is400Weight && isPrimaryIntent,
    'hover:border-primary-500': isBorderPrefix && is500Weight && isPrimaryIntent,
    'hover:border-primary-600': isBorderPrefix && is600Weight && isPrimaryIntent,
    'hover:border-primary-700': isBorderPrefix && is700Weight && isPrimaryIntent,
    'hover:border-primary-800': isBorderPrefix && is800Weight && isPrimaryIntent,
    'hover:border-primary-900': isBorderPrefix && is900Weight && isPrimaryIntent,
    // info
    'hover:border-info-50': isBorderPrefix && is50Weight && isInfoIntent,
    'hover:border-info-100': isBorderPrefix && is100Weight && isInfoIntent,
    'hover:border-info-200': isBorderPrefix && is200Weight && isInfoIntent,
    'hover:border-info-300': isBorderPrefix && is300Weight && isInfoIntent,
    'hover:border-info-400': isBorderPrefix && is400Weight && isInfoIntent,
    'hover:border-info-500': isBorderPrefix && is500Weight && isInfoIntent,
    'hover:border-info-600': isBorderPrefix && is600Weight && isInfoIntent,
    'hover:border-info-700': isBorderPrefix && is700Weight && isInfoIntent,
    'hover:border-info-800': isBorderPrefix && is800Weight && isInfoIntent,
    'hover:border-info-900': isBorderPrefix && is900Weight && isInfoIntent,
    // success
    'hover:border-success-50': isBorderPrefix && is50Weight && isSuccessIntent,
    'hover:border-success-100': isBorderPrefix && is100Weight && isSuccessIntent,
    'hover:border-success-200': isBorderPrefix && is200Weight && isSuccessIntent,
    'hover:border-success-300': isBorderPrefix && is300Weight && isSuccessIntent,
    'hover:border-success-400': isBorderPrefix && is400Weight && isSuccessIntent,
    'hover:border-success-500': isBorderPrefix && is500Weight && isSuccessIntent,
    'hover:border-success-600': isBorderPrefix && is600Weight && isSuccessIntent,
    'hover:border-success-700': isBorderPrefix && is700Weight && isSuccessIntent,
    'hover:border-success-800': isBorderPrefix && is800Weight && isSuccessIntent,
    'hover:border-success-900': isBorderPrefix && is900Weight && isSuccessIntent,
    // warning
    'hover:border-warning-50': isBorderPrefix && is50Weight && isWarningIntent,
    'hover:border-warning-100': isBorderPrefix && is100Weight && isWarningIntent,
    'hover:border-warning-200': isBorderPrefix && is200Weight && isWarningIntent,
    'hover:border-warning-300': isBorderPrefix && is300Weight && isWarningIntent,
    'hover:border-warning-400': isBorderPrefix && is400Weight && isWarningIntent,
    'hover:border-warning-500': isBorderPrefix && is500Weight && isWarningIntent,
    'hover:border-warning-600': isBorderPrefix && is600Weight && isWarningIntent,
    'hover:border-warning-700': isBorderPrefix && is700Weight && isWarningIntent,
    'hover:border-warning-800': isBorderPrefix && is800Weight && isWarningIntent,
    'hover:border-warning-900': isBorderPrefix && is900Weight && isWarningIntent,
    // danger
    'hover:border-danger-50': isBorderPrefix && is50Weight && isDangerIntent,
    'hover:border-danger-100': isBorderPrefix && is100Weight && isDangerIntent,
    'hover:border-danger-200': isBorderPrefix && is200Weight && isDangerIntent,
    'hover:border-danger-300': isBorderPrefix && is300Weight && isDangerIntent,
    'hover:border-danger-400': isBorderPrefix && is400Weight && isDangerIntent,
    'hover:border-danger-500': isBorderPrefix && is500Weight && isDangerIntent,
    'hover:border-danger-600': isBorderPrefix && is600Weight && isDangerIntent,
    'hover:border-danger-700': isBorderPrefix && is700Weight && isDangerIntent,
    'hover:border-danger-800': isBorderPrefix && is800Weight && isDangerIntent,
    'hover:border-danger-900': isBorderPrefix && is900Weight && isDangerIntent,
    /**
     * @name outline
     */
    // light
    'hover:outline-light-50': isOutlinePrefix && is50Weight && isLightIntent,
    'hover:outline-light-100': isOutlinePrefix && is100Weight && isLightIntent,
    'hover:outline-light-200': isOutlinePrefix && is200Weight && isLightIntent,
    'hover:outline-light-300': isOutlinePrefix && is300Weight && isLightIntent,
    'hover:outline-light-400': isOutlinePrefix && is400Weight && isLightIntent,
    'hover:outline-light-500': isOutlinePrefix && is500Weight && isLightIntent,
    'hover:outline-light-600': isOutlinePrefix && is600Weight && isLightIntent,
    'hover:outline-light-700': isOutlinePrefix && is700Weight && isLightIntent,
    'hover:outline-light-800': isOutlinePrefix && is800Weight && isLightIntent,
    'hover:outline-light-900': isOutlinePrefix && is900Weight && isLightIntent,
    // dark
    'hover:outline-dark-50': isOutlinePrefix && is50Weight && isDarkIntent,
    'hover:outline-dark-100': isOutlinePrefix && is100Weight && isDarkIntent,
    'hover:outline-dark-200': isOutlinePrefix && is200Weight && isDarkIntent,
    'hover:outline-dark-300': isOutlinePrefix && is300Weight && isDarkIntent,
    'hover:outline-dark-400': isOutlinePrefix && is400Weight && isDarkIntent,
    'hover:outline-dark-500': isOutlinePrefix && is500Weight && isDarkIntent,
    'hover:outline-dark-600': isOutlinePrefix && is600Weight && isDarkIntent,
    'hover:outline-dark-700': isOutlinePrefix && is700Weight && isDarkIntent,
    'hover:outline-dark-800': isOutlinePrefix && is800Weight && isDarkIntent,
    'hover:outline-dark-900': isOutlinePrefix && is900Weight && isDarkIntent,
    // neutral
    'hover:outline-neutral-50': isOutlinePrefix && is50Weight && isNeutralIntent,
    'hover:outline-neutral-100': isOutlinePrefix && is100Weight && isNeutralIntent,
    'hover:outline-neutral-200': isOutlinePrefix && is200Weight && isNeutralIntent,
    'hover:outline-neutral-300': isOutlinePrefix && is300Weight && isNeutralIntent,
    'hover:outline-neutral-400': isOutlinePrefix && is400Weight && isNeutralIntent,
    'hover:outline-neutral-500': isOutlinePrefix && is500Weight && isNeutralIntent,
    'hover:outline-neutral-600': isOutlinePrefix && is600Weight && isNeutralIntent,
    'hover:outline-neutral-700': isOutlinePrefix && is700Weight && isNeutralIntent,
    'hover:outline-neutral-800': isOutlinePrefix && is800Weight && isNeutralIntent,
    'hover:outline-neutral-900': isOutlinePrefix && is900Weight && isNeutralIntent,
    // primary
    'hover:outline-primary-50': isOutlinePrefix && is50Weight && isPrimaryIntent,
    'hover:outline-primary-100': isOutlinePrefix && is100Weight && isPrimaryIntent,
    'hover:outline-primary-200': isOutlinePrefix && is200Weight && isPrimaryIntent,
    'hover:outline-primary-300': isOutlinePrefix && is300Weight && isPrimaryIntent,
    'hover:outline-primary-400': isOutlinePrefix && is400Weight && isPrimaryIntent,
    'hover:outline-primary-500': isOutlinePrefix && is500Weight && isPrimaryIntent,
    'hover:outline-primary-600': isOutlinePrefix && is600Weight && isPrimaryIntent,
    'hover:outline-primary-700': isOutlinePrefix && is700Weight && isPrimaryIntent,
    'hover:outline-primary-800': isOutlinePrefix && is800Weight && isPrimaryIntent,
    'hover:outline-primary-900': isOutlinePrefix && is900Weight && isPrimaryIntent,
    // info
    'hover:outline-info-50': isOutlinePrefix && is50Weight && isInfoIntent,
    'hover:outline-info-100': isOutlinePrefix && is100Weight && isInfoIntent,
    'hover:outline-info-200': isOutlinePrefix && is200Weight && isInfoIntent,
    'hover:outline-info-300': isOutlinePrefix && is300Weight && isInfoIntent,
    'hover:outline-info-400': isOutlinePrefix && is400Weight && isInfoIntent,
    'hover:outline-info-500': isOutlinePrefix && is500Weight && isInfoIntent,
    'hover:outline-info-600': isOutlinePrefix && is600Weight && isInfoIntent,
    'hover:outline-info-700': isOutlinePrefix && is700Weight && isInfoIntent,
    'hover:outline-info-800': isOutlinePrefix && is800Weight && isInfoIntent,
    'hover:outline-info-900': isOutlinePrefix && is900Weight && isInfoIntent,
    // success
    'hover:outline-success-50': isOutlinePrefix && is50Weight && isSuccessIntent,
    'hover:outline-success-100': isOutlinePrefix && is100Weight && isSuccessIntent,
    'hover:outline-success-200': isOutlinePrefix && is200Weight && isSuccessIntent,
    'hover:outline-success-300': isOutlinePrefix && is300Weight && isSuccessIntent,
    'hover:outline-success-400': isOutlinePrefix && is400Weight && isSuccessIntent,
    'hover:outline-success-500': isOutlinePrefix && is500Weight && isSuccessIntent,
    'hover:outline-success-600': isOutlinePrefix && is600Weight && isSuccessIntent,
    'hover:outline-success-700': isOutlinePrefix && is700Weight && isSuccessIntent,
    'hover:outline-success-800': isOutlinePrefix && is800Weight && isSuccessIntent,
    'hover:outline-success-900': isOutlinePrefix && is900Weight && isSuccessIntent,
    // warning
    'hover:outline-warning-50': isOutlinePrefix && is50Weight && isWarningIntent,
    'hover:outline-warning-100': isOutlinePrefix && is100Weight && isWarningIntent,
    'hover:outline-warning-200': isOutlinePrefix && is200Weight && isWarningIntent,
    'hover:outline-warning-300': isOutlinePrefix && is300Weight && isWarningIntent,
    'hover:outline-warning-400': isOutlinePrefix && is400Weight && isWarningIntent,
    'hover:outline-warning-500': isOutlinePrefix && is500Weight && isWarningIntent,
    'hover:outline-warning-600': isOutlinePrefix && is600Weight && isWarningIntent,
    'hover:outline-warning-700': isOutlinePrefix && is700Weight && isWarningIntent,
    'hover:outline-warning-800': isOutlinePrefix && is800Weight && isWarningIntent,
    'hover:outline-warning-900': isOutlinePrefix && is900Weight && isWarningIntent,
    // danger
    'hover:outline-danger-50': isOutlinePrefix && is50Weight && isDangerIntent,
    'hover:outline-danger-100': isOutlinePrefix && is100Weight && isDangerIntent,
    'hover:outline-danger-200': isOutlinePrefix && is200Weight && isDangerIntent,
    'hover:outline-danger-300': isOutlinePrefix && is300Weight && isDangerIntent,
    'hover:outline-danger-400': isOutlinePrefix && is400Weight && isDangerIntent,
    'hover:outline-danger-500': isOutlinePrefix && is500Weight && isDangerIntent,
    'hover:outline-danger-600': isOutlinePrefix && is600Weight && isDangerIntent,
    'hover:outline-danger-700': isOutlinePrefix && is700Weight && isDangerIntent,
    'hover:outline-danger-800': isOutlinePrefix && is800Weight && isDangerIntent,
    'hover:outline-danger-900': isOutlinePrefix && is900Weight && isDangerIntent,
    /**
     * @name ring
     */
    // light
    'hover:ring-light-50': isRingPrefix && is50Weight && isLightIntent,
    'hover:ring-light-100': isRingPrefix && is100Weight && isLightIntent,
    'hover:ring-light-200': isRingPrefix && is200Weight && isLightIntent,
    'hover:ring-light-300': isRingPrefix && is300Weight && isLightIntent,
    'hover:ring-light-400': isRingPrefix && is400Weight && isLightIntent,
    'hover:ring-light-500': isRingPrefix && is500Weight && isLightIntent,
    'hover:ring-light-600': isRingPrefix && is600Weight && isLightIntent,
    'hover:ring-light-700': isRingPrefix && is700Weight && isLightIntent,
    'hover:ring-light-800': isRingPrefix && is800Weight && isLightIntent,
    'hover:ring-light-900': isRingPrefix && is900Weight && isLightIntent,
    // dark
    'hover:ring-dark-50': isRingPrefix && is50Weight && isDarkIntent,
    'hover:ring-dark-100': isRingPrefix && is100Weight && isDarkIntent,
    'hover:ring-dark-200': isRingPrefix && is200Weight && isDarkIntent,
    'hover:ring-dark-300': isRingPrefix && is300Weight && isDarkIntent,
    'hover:ring-dark-400': isRingPrefix && is400Weight && isDarkIntent,
    'hover:ring-dark-500': isRingPrefix && is500Weight && isDarkIntent,
    'hover:ring-dark-600': isRingPrefix && is600Weight && isDarkIntent,
    'hover:ring-dark-700': isRingPrefix && is700Weight && isDarkIntent,
    'hover:ring-dark-800': isRingPrefix && is800Weight && isDarkIntent,
    'hover:ring-dark-900': isRingPrefix && is900Weight && isDarkIntent,
    // neutral
    'hover:ring-neutral-50': isRingPrefix && is50Weight && isNeutralIntent,
    'hover:ring-neutral-100': isRingPrefix && is100Weight && isNeutralIntent,
    'hover:ring-neutral-200': isRingPrefix && is200Weight && isNeutralIntent,
    'hover:ring-neutral-300': isRingPrefix && is300Weight && isNeutralIntent,
    'hover:ring-neutral-400': isRingPrefix && is400Weight && isNeutralIntent,
    'hover:ring-neutral-500': isRingPrefix && is500Weight && isNeutralIntent,
    'hover:ring-neutral-600': isRingPrefix && is600Weight && isNeutralIntent,
    'hover:ring-neutral-700': isRingPrefix && is700Weight && isNeutralIntent,
    'hover:ring-neutral-800': isRingPrefix && is800Weight && isNeutralIntent,
    'hover:ring-neutral-900': isRingPrefix && is900Weight && isNeutralIntent,
    // primary
    'hover:ring-primary-50': isRingPrefix && is50Weight && isPrimaryIntent,
    'hover:ring-primary-100': isRingPrefix && is100Weight && isPrimaryIntent,
    'hover:ring-primary-200': isRingPrefix && is200Weight && isPrimaryIntent,
    'hover:ring-primary-300': isRingPrefix && is300Weight && isPrimaryIntent,
    'hover:ring-primary-400': isRingPrefix && is400Weight && isPrimaryIntent,
    'hover:ring-primary-500': isRingPrefix && is500Weight && isPrimaryIntent,
    'hover:ring-primary-600': isRingPrefix && is600Weight && isPrimaryIntent,
    'hover:ring-primary-700': isRingPrefix && is700Weight && isPrimaryIntent,
    'hover:ring-primary-800': isRingPrefix && is800Weight && isPrimaryIntent,
    'hover:ring-primary-900': isRingPrefix && is900Weight && isPrimaryIntent,
    // info
    'hover:ring-info-50': isRingPrefix && is50Weight && isInfoIntent,
    'hover:ring-info-100': isRingPrefix && is100Weight && isInfoIntent,
    'hover:ring-info-200': isRingPrefix && is200Weight && isInfoIntent,
    'hover:ring-info-300': isRingPrefix && is300Weight && isInfoIntent,
    'hover:ring-info-400': isRingPrefix && is400Weight && isInfoIntent,
    'hover:ring-info-500': isRingPrefix && is500Weight && isInfoIntent,
    'hover:ring-info-600': isRingPrefix && is600Weight && isInfoIntent,
    'hover:ring-info-700': isRingPrefix && is700Weight && isInfoIntent,
    'hover:ring-info-800': isRingPrefix && is800Weight && isInfoIntent,
    'hover:ring-info-900': isRingPrefix && is900Weight && isInfoIntent,
    // success
    'hover:ring-success-50': isRingPrefix && is50Weight && isSuccessIntent,
    'hover:ring-success-100': isRingPrefix && is100Weight && isSuccessIntent,
    'hover:ring-success-200': isRingPrefix && is200Weight && isSuccessIntent,
    'hover:ring-success-300': isRingPrefix && is300Weight && isSuccessIntent,
    'hover:ring-success-400': isRingPrefix && is400Weight && isSuccessIntent,
    'hover:ring-success-500': isRingPrefix && is500Weight && isSuccessIntent,
    'hover:ring-success-600': isRingPrefix && is600Weight && isSuccessIntent,
    'hover:ring-success-700': isRingPrefix && is700Weight && isSuccessIntent,
    'hover:ring-success-800': isRingPrefix && is800Weight && isSuccessIntent,
    'hover:ring-success-900': isRingPrefix && is900Weight && isSuccessIntent,
    // warning
    'hover:ring-warning-50': isRingPrefix && is50Weight && isWarningIntent,
    'hover:ring-warning-100': isRingPrefix && is100Weight && isWarningIntent,
    'hover:ring-warning-200': isRingPrefix && is200Weight && isWarningIntent,
    'hover:ring-warning-300': isRingPrefix && is300Weight && isWarningIntent,
    'hover:ring-warning-400': isRingPrefix && is400Weight && isWarningIntent,
    'hover:ring-warning-500': isRingPrefix && is500Weight && isWarningIntent,
    'hover:ring-warning-600': isRingPrefix && is600Weight && isWarningIntent,
    'hover:ring-warning-700': isRingPrefix && is700Weight && isWarningIntent,
    'hover:ring-warning-800': isRingPrefix && is800Weight && isWarningIntent,
    'hover:ring-warning-900': isRingPrefix && is900Weight && isWarningIntent,
    // danger
    'hover:ring-danger-50': isRingPrefix && is50Weight && isDangerIntent,
    'hover:ring-danger-100': isRingPrefix && is100Weight && isDangerIntent,
    'hover:ring-danger-200': isRingPrefix && is200Weight && isDangerIntent,
    'hover:ring-danger-300': isRingPrefix && is300Weight && isDangerIntent,
    'hover:ring-danger-400': isRingPrefix && is400Weight && isDangerIntent,
    'hover:ring-danger-500': isRingPrefix && is500Weight && isDangerIntent,
    'hover:ring-danger-600': isRingPrefix && is600Weight && isDangerIntent,
    'hover:ring-danger-700': isRingPrefix && is700Weight && isDangerIntent,
    'hover:ring-danger-800': isRingPrefix && is800Weight && isDangerIntent,
    'hover:ring-danger-900': isRingPrefix && is900Weight && isDangerIntent,
    /**
     * @name ring-offset
     */
    // light
    'hover:ring-offset-light-50': isRingOffsetPrefix && is50Weight && isLightIntent,
    'hover:ring-offset-light-100': isRingOffsetPrefix && is100Weight && isLightIntent,
    'hover:ring-offset-light-200': isRingOffsetPrefix && is200Weight && isLightIntent,
    'hover:ring-offset-light-300': isRingOffsetPrefix && is300Weight && isLightIntent,
    'hover:ring-offset-light-400': isRingOffsetPrefix && is400Weight && isLightIntent,
    'hover:ring-offset-light-500': isRingOffsetPrefix && is500Weight && isLightIntent,
    'hover:ring-offset-light-600': isRingOffsetPrefix && is600Weight && isLightIntent,
    'hover:ring-offset-light-700': isRingOffsetPrefix && is700Weight && isLightIntent,
    'hover:ring-offset-light-800': isRingOffsetPrefix && is800Weight && isLightIntent,
    'hover:ring-offset-light-900': isRingOffsetPrefix && is900Weight && isLightIntent,
    // dark
    'hover:ring-offset-dark-50': isRingOffsetPrefix && is50Weight && isDarkIntent,
    'hover:ring-offset-dark-100': isRingOffsetPrefix && is100Weight && isDarkIntent,
    'hover:ring-offset-dark-200': isRingOffsetPrefix && is200Weight && isDarkIntent,
    'hover:ring-offset-dark-300': isRingOffsetPrefix && is300Weight && isDarkIntent,
    'hover:ring-offset-dark-400': isRingOffsetPrefix && is400Weight && isDarkIntent,
    'hover:ring-offset-dark-500': isRingOffsetPrefix && is500Weight && isDarkIntent,
    'hover:ring-offset-dark-600': isRingOffsetPrefix && is600Weight && isDarkIntent,
    'hover:ring-offset-dark-700': isRingOffsetPrefix && is700Weight && isDarkIntent,
    'hover:ring-offset-dark-800': isRingOffsetPrefix && is800Weight && isDarkIntent,
    'hover:ring-offset-dark-900': isRingOffsetPrefix && is900Weight && isDarkIntent,
    // neutral
    'hover:ring-offset-neutral-50': isRingOffsetPrefix && is50Weight && isNeutralIntent,
    'hover:ring-offset-neutral-100': isRingOffsetPrefix && is100Weight && isNeutralIntent,
    'hover:ring-offset-neutral-200': isRingOffsetPrefix && is200Weight && isNeutralIntent,
    'hover:ring-offset-neutral-300': isRingOffsetPrefix && is300Weight && isNeutralIntent,
    'hover:ring-offset-neutral-400': isRingOffsetPrefix && is400Weight && isNeutralIntent,
    'hover:ring-offset-neutral-500': isRingOffsetPrefix && is500Weight && isNeutralIntent,
    'hover:ring-offset-neutral-600': isRingOffsetPrefix && is600Weight && isNeutralIntent,
    'hover:ring-offset-neutral-700': isRingOffsetPrefix && is700Weight && isNeutralIntent,
    'hover:ring-offset-neutral-800': isRingOffsetPrefix && is800Weight && isNeutralIntent,
    'hover:ring-offset-neutral-900': isRingOffsetPrefix && is900Weight && isNeutralIntent,
    // primary
    'hover:ring-offset-primary-50': isRingOffsetPrefix && is50Weight && isPrimaryIntent,
    'hover:ring-offset-primary-100': isRingOffsetPrefix && is100Weight && isPrimaryIntent,
    'hover:ring-offset-primary-200': isRingOffsetPrefix && is200Weight && isPrimaryIntent,
    'hover:ring-offset-primary-300': isRingOffsetPrefix && is300Weight && isPrimaryIntent,
    'hover:ring-offset-primary-400': isRingOffsetPrefix && is400Weight && isPrimaryIntent,
    'hover:ring-offset-primary-500': isRingOffsetPrefix && is500Weight && isPrimaryIntent,
    'hover:ring-offset-primary-600': isRingOffsetPrefix && is600Weight && isPrimaryIntent,
    'hover:ring-offset-primary-700': isRingOffsetPrefix && is700Weight && isPrimaryIntent,
    'hover:ring-offset-primary-800': isRingOffsetPrefix && is800Weight && isPrimaryIntent,
    'hover:ring-offset-primary-900': isRingOffsetPrefix && is900Weight && isPrimaryIntent,
    // info
    'hover:ring-offset-info-50': isRingOffsetPrefix && is50Weight && isInfoIntent,
    'hover:ring-offset-info-100': isRingOffsetPrefix && is100Weight && isInfoIntent,
    'hover:ring-offset-info-200': isRingOffsetPrefix && is200Weight && isInfoIntent,
    'hover:ring-offset-info-300': isRingOffsetPrefix && is300Weight && isInfoIntent,
    'hover:ring-offset-info-400': isRingOffsetPrefix && is400Weight && isInfoIntent,
    'hover:ring-offset-info-500': isRingOffsetPrefix && is500Weight && isInfoIntent,
    'hover:ring-offset-info-600': isRingOffsetPrefix && is600Weight && isInfoIntent,
    'hover:ring-offset-info-700': isRingOffsetPrefix && is700Weight && isInfoIntent,
    'hover:ring-offset-info-800': isRingOffsetPrefix && is800Weight && isInfoIntent,
    'hover:ring-offset-info-900': isRingOffsetPrefix && is900Weight && isInfoIntent,
    // success
    'hover:ring-offset-success-50': isRingOffsetPrefix && is50Weight && isSuccessIntent,
    'hover:ring-offset-success-100': isRingOffsetPrefix && is100Weight && isSuccessIntent,
    'hover:ring-offset-success-200': isRingOffsetPrefix && is200Weight && isSuccessIntent,
    'hover:ring-offset-success-300': isRingOffsetPrefix && is300Weight && isSuccessIntent,
    'hover:ring-offset-success-400': isRingOffsetPrefix && is400Weight && isSuccessIntent,
    'hover:ring-offset-success-500': isRingOffsetPrefix && is500Weight && isSuccessIntent,
    'hover:ring-offset-success-600': isRingOffsetPrefix && is600Weight && isSuccessIntent,
    'hover:ring-offset-success-700': isRingOffsetPrefix && is700Weight && isSuccessIntent,
    'hover:ring-offset-success-800': isRingOffsetPrefix && is800Weight && isSuccessIntent,
    'hover:ring-offset-success-900': isRingOffsetPrefix && is900Weight && isSuccessIntent,
    // warning
    'hover:ring-offset-warning-50': isRingOffsetPrefix && is50Weight && isWarningIntent,
    'hover:ring-offset-warning-100': isRingOffsetPrefix && is100Weight && isWarningIntent,
    'hover:ring-offset-warning-200': isRingOffsetPrefix && is200Weight && isWarningIntent,
    'hover:ring-offset-warning-300': isRingOffsetPrefix && is300Weight && isWarningIntent,
    'hover:ring-offset-warning-400': isRingOffsetPrefix && is400Weight && isWarningIntent,
    'hover:ring-offset-warning-500': isRingOffsetPrefix && is500Weight && isWarningIntent,
    'hover:ring-offset-warning-600': isRingOffsetPrefix && is600Weight && isWarningIntent,
    'hover:ring-offset-warning-700': isRingOffsetPrefix && is700Weight && isWarningIntent,
    'hover:ring-offset-warning-800': isRingOffsetPrefix && is800Weight && isWarningIntent,
    'hover:ring-offset-warning-900': isRingOffsetPrefix && is900Weight && isWarningIntent,
    // danger
    'hover:ring-offset-danger-50': isRingOffsetPrefix && is50Weight && isDangerIntent,
    'hover:ring-offset-danger-100': isRingOffsetPrefix && is100Weight && isDangerIntent,
    'hover:ring-offset-danger-200': isRingOffsetPrefix && is200Weight && isDangerIntent,
    'hover:ring-offset-danger-300': isRingOffsetPrefix && is300Weight && isDangerIntent,
    'hover:ring-offset-danger-400': isRingOffsetPrefix && is400Weight && isDangerIntent,
    'hover:ring-offset-danger-500': isRingOffsetPrefix && is500Weight && isDangerIntent,
    'hover:ring-offset-danger-600': isRingOffsetPrefix && is600Weight && isDangerIntent,
    'hover:ring-offset-danger-700': isRingOffsetPrefix && is700Weight && isDangerIntent,
    'hover:ring-offset-danger-800': isRingOffsetPrefix && is800Weight && isDangerIntent,
    'hover:ring-offset-danger-900': isRingOffsetPrefix && is900Weight && isDangerIntent,
    /**
     * @name fill
     */
    // light
    'hover:fill-light-50': isFillPrefix && is50Weight && isLightIntent,
    'hover:fill-light-100': isFillPrefix && is100Weight && isLightIntent,
    'hover:fill-light-200': isFillPrefix && is200Weight && isLightIntent,
    'hover:fill-light-300': isFillPrefix && is300Weight && isLightIntent,
    'hover:fill-light-400': isFillPrefix && is400Weight && isLightIntent,
    'hover:fill-light-500': isFillPrefix && is500Weight && isLightIntent,
    'hover:fill-light-600': isFillPrefix && is600Weight && isLightIntent,
    'hover:fill-light-700': isFillPrefix && is700Weight && isLightIntent,
    'hover:fill-light-800': isFillPrefix && is800Weight && isLightIntent,
    'hover:fill-light-900': isFillPrefix && is900Weight && isLightIntent,
    // dark
    'hover:fill-dark-50': isFillPrefix && is50Weight && isDarkIntent,
    'hover:fill-dark-100': isFillPrefix && is100Weight && isDarkIntent,
    'hover:fill-dark-200': isFillPrefix && is200Weight && isDarkIntent,
    'hover:fill-dark-300': isFillPrefix && is300Weight && isDarkIntent,
    'hover:fill-dark-400': isFillPrefix && is400Weight && isDarkIntent,
    'hover:fill-dark-500': isFillPrefix && is500Weight && isDarkIntent,
    'hover:fill-dark-600': isFillPrefix && is600Weight && isDarkIntent,
    'hover:fill-dark-700': isFillPrefix && is700Weight && isDarkIntent,
    'hover:fill-dark-800': isFillPrefix && is800Weight && isDarkIntent,
    'hover:fill-dark-900': isFillPrefix && is900Weight && isDarkIntent,
    // neutral
    'hover:fill-neutral-50': isFillPrefix && is50Weight && isNeutralIntent,
    'hover:fill-neutral-100': isFillPrefix && is100Weight && isNeutralIntent,
    'hover:fill-neutral-200': isFillPrefix && is200Weight && isNeutralIntent,
    'hover:fill-neutral-300': isFillPrefix && is300Weight && isNeutralIntent,
    'hover:fill-neutral-400': isFillPrefix && is400Weight && isNeutralIntent,
    'hover:fill-neutral-500': isFillPrefix && is500Weight && isNeutralIntent,
    'hover:fill-neutral-600': isFillPrefix && is600Weight && isNeutralIntent,
    'hover:fill-neutral-700': isFillPrefix && is700Weight && isNeutralIntent,
    'hover:fill-neutral-800': isFillPrefix && is800Weight && isNeutralIntent,
    'hover:fill-neutral-900': isFillPrefix && is900Weight && isNeutralIntent,
    // primary
    'hover:fill-primary-50': isFillPrefix && is50Weight && isPrimaryIntent,
    'hover:fill-primary-100': isFillPrefix && is100Weight && isPrimaryIntent,
    'hover:fill-primary-200': isFillPrefix && is200Weight && isPrimaryIntent,
    'hover:fill-primary-300': isFillPrefix && is300Weight && isPrimaryIntent,
    'hover:fill-primary-400': isFillPrefix && is400Weight && isPrimaryIntent,
    'hover:fill-primary-500': isFillPrefix && is500Weight && isPrimaryIntent,
    'hover:fill-primary-600': isFillPrefix && is600Weight && isPrimaryIntent,
    'hover:fill-primary-700': isFillPrefix && is700Weight && isPrimaryIntent,
    'hover:fill-primary-800': isFillPrefix && is800Weight && isPrimaryIntent,
    'hover:fill-primary-900': isFillPrefix && is900Weight && isPrimaryIntent,
    // info
    'hover:fill-info-50': isFillPrefix && is50Weight && isInfoIntent,
    'hover:fill-info-100': isFillPrefix && is100Weight && isInfoIntent,
    'hover:fill-info-200': isFillPrefix && is200Weight && isInfoIntent,
    'hover:fill-info-300': isFillPrefix && is300Weight && isInfoIntent,
    'hover:fill-info-400': isFillPrefix && is400Weight && isInfoIntent,
    'hover:fill-info-500': isFillPrefix && is500Weight && isInfoIntent,
    'hover:fill-info-600': isFillPrefix && is600Weight && isInfoIntent,
    'hover:fill-info-700': isFillPrefix && is700Weight && isInfoIntent,
    'hover:fill-info-800': isFillPrefix && is800Weight && isInfoIntent,
    'hover:fill-info-900': isFillPrefix && is900Weight && isInfoIntent,
    // success
    'hover:fill-success-50': isFillPrefix && is50Weight && isSuccessIntent,
    'hover:fill-success-100': isFillPrefix && is100Weight && isSuccessIntent,
    'hover:fill-success-200': isFillPrefix && is200Weight && isSuccessIntent,
    'hover:fill-success-300': isFillPrefix && is300Weight && isSuccessIntent,
    'hover:fill-success-400': isFillPrefix && is400Weight && isSuccessIntent,
    'hover:fill-success-500': isFillPrefix && is500Weight && isSuccessIntent,
    'hover:fill-success-600': isFillPrefix && is600Weight && isSuccessIntent,
    'hover:fill-success-700': isFillPrefix && is700Weight && isSuccessIntent,
    'hover:fill-success-800': isFillPrefix && is800Weight && isSuccessIntent,
    'hover:fill-success-900': isFillPrefix && is900Weight && isSuccessIntent,
    // warning
    'hover:fill-warning-50': isFillPrefix && is50Weight && isWarningIntent,
    'hover:fill-warning-100': isFillPrefix && is100Weight && isWarningIntent,
    'hover:fill-warning-200': isFillPrefix && is200Weight && isWarningIntent,
    'hover:fill-warning-300': isFillPrefix && is300Weight && isWarningIntent,
    'hover:fill-warning-400': isFillPrefix && is400Weight && isWarningIntent,
    'hover:fill-warning-500': isFillPrefix && is500Weight && isWarningIntent,
    'hover:fill-warning-600': isFillPrefix && is600Weight && isWarningIntent,
    'hover:fill-warning-700': isFillPrefix && is700Weight && isWarningIntent,
    'hover:fill-warning-800': isFillPrefix && is800Weight && isWarningIntent,
    'hover:fill-warning-900': isFillPrefix && is900Weight && isWarningIntent,
    // danger
    'hover:fill-danger-50': isFillPrefix && is50Weight && isDangerIntent,
    'hover:fill-danger-100': isFillPrefix && is100Weight && isDangerIntent,
    'hover:fill-danger-200': isFillPrefix && is200Weight && isDangerIntent,
    'hover:fill-danger-300': isFillPrefix && is300Weight && isDangerIntent,
    'hover:fill-danger-400': isFillPrefix && is400Weight && isDangerIntent,
    'hover:fill-danger-500': isFillPrefix && is500Weight && isDangerIntent,
    'hover:fill-danger-600': isFillPrefix && is600Weight && isDangerIntent,
    'hover:fill-danger-700': isFillPrefix && is700Weight && isDangerIntent,
    'hover:fill-danger-800': isFillPrefix && is800Weight && isDangerIntent,
    'hover:fill-danger-900': isFillPrefix && is900Weight && isDangerIntent,
  });
};
