import classNames from 'classnames';

import { TailwindPrefix, IntentWeightType, IntentType } from '@/system';

export interface ToIntentColorProps {
  prefix: TailwindPrefix;

  /**
   * @default primary
   */
  intent?: IntentType;

  /**
   * @default 500
   */
  intentWeight?: IntentWeightType;
}

export function toIntentColorVariables({ prefix, intent = 'primary', intentWeight = 500 }: ToIntentColorProps) {
  // Prefix
  const isTextPrefix = prefix === 'text';
  const isBGPrefix = prefix === 'bg';
  const isBorderPrefix = prefix === 'border';
  const isOutlinePrefix = prefix === 'outline';
  const isRingPrefix = prefix === 'ring';
  const isRingOffsetPrefix = prefix === 'ring-offset';
  const isFillPrefix = prefix === 'fill';
  // Weight
  const is50Weight = intentWeight === 50;
  const is100Weight = intentWeight === 100;
  const is200Weight = intentWeight === 200;
  const is300Weight = intentWeight === 300;
  const is400Weight = intentWeight === 400;
  const is500Weight = intentWeight === 500;
  const is600Weight = intentWeight === 600;
  const is700Weight = intentWeight === 700;
  const is800Weight = intentWeight === 800;
  const is900Weight = intentWeight === 900;
  // Intent
  const isLightIntent = intent === 'light';
  const isDarkIntent = intent === 'dark';
  const isNeutralIntent = intent === 'neutral';
  const isPrimaryIntent = intent === 'primary';
  const isInfoIntent = intent === 'info';
  const isSuccessIntent = intent === 'success';
  const isWarningIntent = intent === 'warning';
  const isDangerIntent = intent === 'danger';

  return {
    isTextPrefix,
    isBGPrefix,
    isBorderPrefix,
    isOutlinePrefix,
    isRingPrefix,
    isRingOffsetPrefix,
    isFillPrefix,
    is50Weight,
    is100Weight,
    is200Weight,
    is300Weight,
    is400Weight,
    is500Weight,
    is600Weight,
    is700Weight,
    is800Weight,
    is900Weight,
    isLightIntent,
    isDarkIntent,
    isNeutralIntent,
    isPrimaryIntent,
    isInfoIntent,
    isSuccessIntent,
    isWarningIntent,
    isDangerIntent,
  };
}

/**
 * Tailwind optimization can't recognize template string
 * Must be exports full class string
 */
export function toIntentColor({ prefix, intent = 'primary', intentWeight = 500 }: ToIntentColorProps) {
  const {
    isTextPrefix,
    isBGPrefix,
    isBorderPrefix,
    isOutlinePrefix,
    isRingPrefix,
    isRingOffsetPrefix,
    isFillPrefix,
    is50Weight,
    is100Weight,
    is200Weight,
    is300Weight,
    is400Weight,
    is500Weight,
    is600Weight,
    is700Weight,
    is800Weight,
    is900Weight,
    isLightIntent,
    isDarkIntent,
    isNeutralIntent,
    isPrimaryIntent,
    isInfoIntent,
    isSuccessIntent,
    isWarningIntent,
    isDangerIntent,
  } = toIntentColorVariables({
    prefix,
    intent,
    intentWeight,
  });

  return classNames({
    /**
     * @name text
     */
    // light
    'text-light-50': isTextPrefix && is50Weight && isLightIntent,
    'text-light-100': isTextPrefix && is100Weight && isLightIntent,
    'text-light-200': isTextPrefix && is200Weight && isLightIntent,
    'text-light-300': isTextPrefix && is300Weight && isLightIntent,
    'text-light-400': isTextPrefix && is400Weight && isLightIntent,
    'text-light-500': isTextPrefix && is500Weight && isLightIntent,
    'text-light-600': isTextPrefix && is600Weight && isLightIntent,
    'text-light-700': isTextPrefix && is700Weight && isLightIntent,
    'text-light-800': isTextPrefix && is800Weight && isLightIntent,
    'text-light-900': isTextPrefix && is900Weight && isLightIntent,
    // dark
    'text-dark-50': isTextPrefix && is50Weight && isDarkIntent,
    'text-dark-100': isTextPrefix && is100Weight && isDarkIntent,
    'text-dark-200': isTextPrefix && is200Weight && isDarkIntent,
    'text-dark-300': isTextPrefix && is300Weight && isDarkIntent,
    'text-dark-400': isTextPrefix && is400Weight && isDarkIntent,
    'text-dark-500': isTextPrefix && is500Weight && isDarkIntent,
    'text-dark-600': isTextPrefix && is600Weight && isDarkIntent,
    'text-dark-700': isTextPrefix && is700Weight && isDarkIntent,
    'text-dark-800': isTextPrefix && is800Weight && isDarkIntent,
    'text-dark-900': isTextPrefix && is900Weight && isDarkIntent,
    // neutral
    'text-neutral-50': isTextPrefix && is50Weight && isNeutralIntent,
    'text-neutral-100': isTextPrefix && is100Weight && isNeutralIntent,
    'text-neutral-200': isTextPrefix && is200Weight && isNeutralIntent,
    'text-neutral-300': isTextPrefix && is300Weight && isNeutralIntent,
    'text-neutral-400': isTextPrefix && is400Weight && isNeutralIntent,
    'text-neutral-500': isTextPrefix && is500Weight && isNeutralIntent,
    'text-neutral-600': isTextPrefix && is600Weight && isNeutralIntent,
    'text-neutral-700': isTextPrefix && is700Weight && isNeutralIntent,
    'text-neutral-800': isTextPrefix && is800Weight && isNeutralIntent,
    'text-neutral-900': isTextPrefix && is900Weight && isNeutralIntent,
    // primary
    'text-primary-50': isTextPrefix && is50Weight && isPrimaryIntent,
    'text-primary-100': isTextPrefix && is100Weight && isPrimaryIntent,
    'text-primary-200': isTextPrefix && is200Weight && isPrimaryIntent,
    'text-primary-300': isTextPrefix && is300Weight && isPrimaryIntent,
    'text-primary-400': isTextPrefix && is400Weight && isPrimaryIntent,
    'text-primary-500': isTextPrefix && is500Weight && isPrimaryIntent,
    'text-primary-600': isTextPrefix && is600Weight && isPrimaryIntent,
    'text-primary-700': isTextPrefix && is700Weight && isPrimaryIntent,
    'text-primary-800': isTextPrefix && is800Weight && isPrimaryIntent,
    'text-primary-900': isTextPrefix && is900Weight && isPrimaryIntent,
    // info
    'text-info-50': isTextPrefix && is50Weight && isInfoIntent,
    'text-info-100': isTextPrefix && is100Weight && isInfoIntent,
    'text-info-200': isTextPrefix && is200Weight && isInfoIntent,
    'text-info-300': isTextPrefix && is300Weight && isInfoIntent,
    'text-info-400': isTextPrefix && is400Weight && isInfoIntent,
    'text-info-500': isTextPrefix && is500Weight && isInfoIntent,
    'text-info-600': isTextPrefix && is600Weight && isInfoIntent,
    'text-info-700': isTextPrefix && is700Weight && isInfoIntent,
    'text-info-800': isTextPrefix && is800Weight && isInfoIntent,
    'text-info-900': isTextPrefix && is900Weight && isInfoIntent,
    // success
    'text-success-50': isTextPrefix && is50Weight && isSuccessIntent,
    'text-success-100': isTextPrefix && is100Weight && isSuccessIntent,
    'text-success-200': isTextPrefix && is200Weight && isSuccessIntent,
    'text-success-300': isTextPrefix && is300Weight && isSuccessIntent,
    'text-success-400': isTextPrefix && is400Weight && isSuccessIntent,
    'text-success-500': isTextPrefix && is500Weight && isSuccessIntent,
    'text-success-600': isTextPrefix && is600Weight && isSuccessIntent,
    'text-success-700': isTextPrefix && is700Weight && isSuccessIntent,
    'text-success-800': isTextPrefix && is800Weight && isSuccessIntent,
    'text-success-900': isTextPrefix && is900Weight && isSuccessIntent,
    // warning
    'text-warning-50': isTextPrefix && is50Weight && isWarningIntent,
    'text-warning-100': isTextPrefix && is100Weight && isWarningIntent,
    'text-warning-200': isTextPrefix && is200Weight && isWarningIntent,
    'text-warning-300': isTextPrefix && is300Weight && isWarningIntent,
    'text-warning-400': isTextPrefix && is400Weight && isWarningIntent,
    'text-warning-500': isTextPrefix && is500Weight && isWarningIntent,
    'text-warning-600': isTextPrefix && is600Weight && isWarningIntent,
    'text-warning-700': isTextPrefix && is700Weight && isWarningIntent,
    'text-warning-800': isTextPrefix && is800Weight && isWarningIntent,
    'text-warning-900': isTextPrefix && is900Weight && isWarningIntent,
    // danger
    'text-danger-50': isTextPrefix && is50Weight && isDangerIntent,
    'text-danger-100': isTextPrefix && is100Weight && isDangerIntent,
    'text-danger-200': isTextPrefix && is200Weight && isDangerIntent,
    'text-danger-300': isTextPrefix && is300Weight && isDangerIntent,
    'text-danger-400': isTextPrefix && is400Weight && isDangerIntent,
    'text-danger-500': isTextPrefix && is500Weight && isDangerIntent,
    'text-danger-600': isTextPrefix && is600Weight && isDangerIntent,
    'text-danger-700': isTextPrefix && is700Weight && isDangerIntent,
    'text-danger-800': isTextPrefix && is800Weight && isDangerIntent,
    'text-danger-900': isTextPrefix && is900Weight && isDangerIntent,
    /**
     * @name bg
     */
    // light
    'bg-light-50': isBGPrefix && is50Weight && isLightIntent,
    'bg-light-100': isBGPrefix && is100Weight && isLightIntent,
    'bg-light-200': isBGPrefix && is200Weight && isLightIntent,
    'bg-light-300': isBGPrefix && is300Weight && isLightIntent,
    'bg-light-400': isBGPrefix && is400Weight && isLightIntent,
    'bg-light-500': isBGPrefix && is500Weight && isLightIntent,
    'bg-light-600': isBGPrefix && is600Weight && isLightIntent,
    'bg-light-700': isBGPrefix && is700Weight && isLightIntent,
    'bg-light-800': isBGPrefix && is800Weight && isLightIntent,
    'bg-light-900': isBGPrefix && is900Weight && isLightIntent,
    // dark
    'bg-dark-50': isBGPrefix && is50Weight && isDarkIntent,
    'bg-dark-100': isBGPrefix && is100Weight && isDarkIntent,
    'bg-dark-200': isBGPrefix && is200Weight && isDarkIntent,
    'bg-dark-300': isBGPrefix && is300Weight && isDarkIntent,
    'bg-dark-400': isBGPrefix && is400Weight && isDarkIntent,
    'bg-dark-500': isBGPrefix && is500Weight && isDarkIntent,
    'bg-dark-600': isBGPrefix && is600Weight && isDarkIntent,
    'bg-dark-700': isBGPrefix && is700Weight && isDarkIntent,
    'bg-dark-800': isBGPrefix && is800Weight && isDarkIntent,
    'bg-dark-900': isBGPrefix && is900Weight && isDarkIntent,
    // neutral
    'bg-neutral-50': isBGPrefix && is50Weight && isNeutralIntent,
    'bg-neutral-100': isBGPrefix && is100Weight && isNeutralIntent,
    'bg-neutral-200': isBGPrefix && is200Weight && isNeutralIntent,
    'bg-neutral-300': isBGPrefix && is300Weight && isNeutralIntent,
    'bg-neutral-400': isBGPrefix && is400Weight && isNeutralIntent,
    'bg-neutral-500': isBGPrefix && is500Weight && isNeutralIntent,
    'bg-neutral-600': isBGPrefix && is600Weight && isNeutralIntent,
    'bg-neutral-700': isBGPrefix && is700Weight && isNeutralIntent,
    'bg-neutral-800': isBGPrefix && is800Weight && isNeutralIntent,
    'bg-neutral-900': isBGPrefix && is900Weight && isNeutralIntent,
    // primary
    'bg-primary-50': isBGPrefix && is50Weight && isPrimaryIntent,
    'bg-primary-100': isBGPrefix && is100Weight && isPrimaryIntent,
    'bg-primary-200': isBGPrefix && is200Weight && isPrimaryIntent,
    'bg-primary-300': isBGPrefix && is300Weight && isPrimaryIntent,
    'bg-primary-400': isBGPrefix && is400Weight && isPrimaryIntent,
    'bg-primary-500': isBGPrefix && is500Weight && isPrimaryIntent,
    'bg-primary-600': isBGPrefix && is600Weight && isPrimaryIntent,
    'bg-primary-700': isBGPrefix && is700Weight && isPrimaryIntent,
    'bg-primary-800': isBGPrefix && is800Weight && isPrimaryIntent,
    'bg-primary-900': isBGPrefix && is900Weight && isPrimaryIntent,
    // info
    'bg-info-50': isBGPrefix && is50Weight && isInfoIntent,
    'bg-info-100': isBGPrefix && is100Weight && isInfoIntent,
    'bg-info-200': isBGPrefix && is200Weight && isInfoIntent,
    'bg-info-300': isBGPrefix && is300Weight && isInfoIntent,
    'bg-info-400': isBGPrefix && is400Weight && isInfoIntent,
    'bg-info-500': isBGPrefix && is500Weight && isInfoIntent,
    'bg-info-600': isBGPrefix && is600Weight && isInfoIntent,
    'bg-info-700': isBGPrefix && is700Weight && isInfoIntent,
    'bg-info-800': isBGPrefix && is800Weight && isInfoIntent,
    'bg-info-900': isBGPrefix && is900Weight && isInfoIntent,
    // success
    'bg-success-50': isBGPrefix && is50Weight && isSuccessIntent,
    'bg-success-100': isBGPrefix && is100Weight && isSuccessIntent,
    'bg-success-200': isBGPrefix && is200Weight && isSuccessIntent,
    'bg-success-300': isBGPrefix && is300Weight && isSuccessIntent,
    'bg-success-400': isBGPrefix && is400Weight && isSuccessIntent,
    'bg-success-500': isBGPrefix && is500Weight && isSuccessIntent,
    'bg-success-600': isBGPrefix && is600Weight && isSuccessIntent,
    'bg-success-700': isBGPrefix && is700Weight && isSuccessIntent,
    'bg-success-800': isBGPrefix && is800Weight && isSuccessIntent,
    'bg-success-900': isBGPrefix && is900Weight && isSuccessIntent,
    // warning
    'bg-warning-50': isBGPrefix && is50Weight && isWarningIntent,
    'bg-warning-100': isBGPrefix && is100Weight && isWarningIntent,
    'bg-warning-200': isBGPrefix && is200Weight && isWarningIntent,
    'bg-warning-300': isBGPrefix && is300Weight && isWarningIntent,
    'bg-warning-400': isBGPrefix && is400Weight && isWarningIntent,
    'bg-warning-500': isBGPrefix && is500Weight && isWarningIntent,
    'bg-warning-600': isBGPrefix && is600Weight && isWarningIntent,
    'bg-warning-700': isBGPrefix && is700Weight && isWarningIntent,
    'bg-warning-800': isBGPrefix && is800Weight && isWarningIntent,
    'bg-warning-900': isBGPrefix && is900Weight && isWarningIntent,
    // danger
    'bg-danger-50': isBGPrefix && is50Weight && isDangerIntent,
    'bg-danger-100': isBGPrefix && is100Weight && isDangerIntent,
    'bg-danger-200': isBGPrefix && is200Weight && isDangerIntent,
    'bg-danger-300': isBGPrefix && is300Weight && isDangerIntent,
    'bg-danger-400': isBGPrefix && is400Weight && isDangerIntent,
    'bg-danger-500': isBGPrefix && is500Weight && isDangerIntent,
    'bg-danger-600': isBGPrefix && is600Weight && isDangerIntent,
    'bg-danger-700': isBGPrefix && is700Weight && isDangerIntent,
    'bg-danger-800': isBGPrefix && is800Weight && isDangerIntent,
    'bg-danger-900': isBGPrefix && is900Weight && isDangerIntent,
    /**
     * @name border
     */
    // light
    'border-light-50': isBorderPrefix && is50Weight && isLightIntent,
    'border-light-100': isBorderPrefix && is100Weight && isLightIntent,
    'border-light-200': isBorderPrefix && is200Weight && isLightIntent,
    'border-light-300': isBorderPrefix && is300Weight && isLightIntent,
    'border-light-400': isBorderPrefix && is400Weight && isLightIntent,
    'border-light-500': isBorderPrefix && is500Weight && isLightIntent,
    'border-light-600': isBorderPrefix && is600Weight && isLightIntent,
    'border-light-700': isBorderPrefix && is700Weight && isLightIntent,
    'border-light-800': isBorderPrefix && is800Weight && isLightIntent,
    'border-light-900': isBorderPrefix && is900Weight && isLightIntent,
    // dark
    'border-dark-50': isBorderPrefix && is50Weight && isDarkIntent,
    'border-dark-100': isBorderPrefix && is100Weight && isDarkIntent,
    'border-dark-200': isBorderPrefix && is200Weight && isDarkIntent,
    'border-dark-300': isBorderPrefix && is300Weight && isDarkIntent,
    'border-dark-400': isBorderPrefix && is400Weight && isDarkIntent,
    'border-dark-500': isBorderPrefix && is500Weight && isDarkIntent,
    'border-dark-600': isBorderPrefix && is600Weight && isDarkIntent,
    'border-dark-700': isBorderPrefix && is700Weight && isDarkIntent,
    'border-dark-800': isBorderPrefix && is800Weight && isDarkIntent,
    'border-dark-900': isBorderPrefix && is900Weight && isDarkIntent,
    // neutral
    'border-neutral-50': isBorderPrefix && is50Weight && isNeutralIntent,
    'border-neutral-100': isBorderPrefix && is100Weight && isNeutralIntent,
    'border-neutral-200': isBorderPrefix && is200Weight && isNeutralIntent,
    'border-neutral-300': isBorderPrefix && is300Weight && isNeutralIntent,
    'border-neutral-400': isBorderPrefix && is400Weight && isNeutralIntent,
    'border-neutral-500': isBorderPrefix && is500Weight && isNeutralIntent,
    'border-neutral-600': isBorderPrefix && is600Weight && isNeutralIntent,
    'border-neutral-700': isBorderPrefix && is700Weight && isNeutralIntent,
    'border-neutral-800': isBorderPrefix && is800Weight && isNeutralIntent,
    'border-neutral-900': isBorderPrefix && is900Weight && isNeutralIntent,
    // primary
    'border-primary-50': isBorderPrefix && is50Weight && isPrimaryIntent,
    'border-primary-100': isBorderPrefix && is100Weight && isPrimaryIntent,
    'border-primary-200': isBorderPrefix && is200Weight && isPrimaryIntent,
    'border-primary-300': isBorderPrefix && is300Weight && isPrimaryIntent,
    'border-primary-400': isBorderPrefix && is400Weight && isPrimaryIntent,
    'border-primary-500': isBorderPrefix && is500Weight && isPrimaryIntent,
    'border-primary-600': isBorderPrefix && is600Weight && isPrimaryIntent,
    'border-primary-700': isBorderPrefix && is700Weight && isPrimaryIntent,
    'border-primary-800': isBorderPrefix && is800Weight && isPrimaryIntent,
    'border-primary-900': isBorderPrefix && is900Weight && isPrimaryIntent,
    // info
    'border-info-50': isBorderPrefix && is50Weight && isInfoIntent,
    'border-info-100': isBorderPrefix && is100Weight && isInfoIntent,
    'border-info-200': isBorderPrefix && is200Weight && isInfoIntent,
    'border-info-300': isBorderPrefix && is300Weight && isInfoIntent,
    'border-info-400': isBorderPrefix && is400Weight && isInfoIntent,
    'border-info-500': isBorderPrefix && is500Weight && isInfoIntent,
    'border-info-600': isBorderPrefix && is600Weight && isInfoIntent,
    'border-info-700': isBorderPrefix && is700Weight && isInfoIntent,
    'border-info-800': isBorderPrefix && is800Weight && isInfoIntent,
    'border-info-900': isBorderPrefix && is900Weight && isInfoIntent,
    // success
    'border-success-50': isBorderPrefix && is50Weight && isSuccessIntent,
    'border-success-100': isBorderPrefix && is100Weight && isSuccessIntent,
    'border-success-200': isBorderPrefix && is200Weight && isSuccessIntent,
    'border-success-300': isBorderPrefix && is300Weight && isSuccessIntent,
    'border-success-400': isBorderPrefix && is400Weight && isSuccessIntent,
    'border-success-500': isBorderPrefix && is500Weight && isSuccessIntent,
    'border-success-600': isBorderPrefix && is600Weight && isSuccessIntent,
    'border-success-700': isBorderPrefix && is700Weight && isSuccessIntent,
    'border-success-800': isBorderPrefix && is800Weight && isSuccessIntent,
    'border-success-900': isBorderPrefix && is900Weight && isSuccessIntent,
    // warning
    'border-warning-50': isBorderPrefix && is50Weight && isWarningIntent,
    'border-warning-100': isBorderPrefix && is100Weight && isWarningIntent,
    'border-warning-200': isBorderPrefix && is200Weight && isWarningIntent,
    'border-warning-300': isBorderPrefix && is300Weight && isWarningIntent,
    'border-warning-400': isBorderPrefix && is400Weight && isWarningIntent,
    'border-warning-500': isBorderPrefix && is500Weight && isWarningIntent,
    'border-warning-600': isBorderPrefix && is600Weight && isWarningIntent,
    'border-warning-700': isBorderPrefix && is700Weight && isWarningIntent,
    'border-warning-800': isBorderPrefix && is800Weight && isWarningIntent,
    'border-warning-900': isBorderPrefix && is900Weight && isWarningIntent,
    // danger
    'border-danger-50': isBorderPrefix && is50Weight && isDangerIntent,
    'border-danger-100': isBorderPrefix && is100Weight && isDangerIntent,
    'border-danger-200': isBorderPrefix && is200Weight && isDangerIntent,
    'border-danger-300': isBorderPrefix && is300Weight && isDangerIntent,
    'border-danger-400': isBorderPrefix && is400Weight && isDangerIntent,
    'border-danger-500': isBorderPrefix && is500Weight && isDangerIntent,
    'border-danger-600': isBorderPrefix && is600Weight && isDangerIntent,
    'border-danger-700': isBorderPrefix && is700Weight && isDangerIntent,
    'border-danger-800': isBorderPrefix && is800Weight && isDangerIntent,
    'border-danger-900': isBorderPrefix && is900Weight && isDangerIntent,
    /**
     * @name outline
     */
    // light
    'outline-light-50': isOutlinePrefix && is50Weight && isLightIntent,
    'outline-light-100': isOutlinePrefix && is100Weight && isLightIntent,
    'outline-light-200': isOutlinePrefix && is200Weight && isLightIntent,
    'outline-light-300': isOutlinePrefix && is300Weight && isLightIntent,
    'outline-light-400': isOutlinePrefix && is400Weight && isLightIntent,
    'outline-light-500': isOutlinePrefix && is500Weight && isLightIntent,
    'outline-light-600': isOutlinePrefix && is600Weight && isLightIntent,
    'outline-light-700': isOutlinePrefix && is700Weight && isLightIntent,
    'outline-light-800': isOutlinePrefix && is800Weight && isLightIntent,
    'outline-light-900': isOutlinePrefix && is900Weight && isLightIntent,
    // dark
    'outline-dark-50': isOutlinePrefix && is50Weight && isDarkIntent,
    'outline-dark-100': isOutlinePrefix && is100Weight && isDarkIntent,
    'outline-dark-200': isOutlinePrefix && is200Weight && isDarkIntent,
    'outline-dark-300': isOutlinePrefix && is300Weight && isDarkIntent,
    'outline-dark-400': isOutlinePrefix && is400Weight && isDarkIntent,
    'outline-dark-500': isOutlinePrefix && is500Weight && isDarkIntent,
    'outline-dark-600': isOutlinePrefix && is600Weight && isDarkIntent,
    'outline-dark-700': isOutlinePrefix && is700Weight && isDarkIntent,
    'outline-dark-800': isOutlinePrefix && is800Weight && isDarkIntent,
    'outline-dark-900': isOutlinePrefix && is900Weight && isDarkIntent,
    // neutral
    'outline-neutral-50': isOutlinePrefix && is50Weight && isNeutralIntent,
    'outline-neutral-100': isOutlinePrefix && is100Weight && isNeutralIntent,
    'outline-neutral-200': isOutlinePrefix && is200Weight && isNeutralIntent,
    'outline-neutral-300': isOutlinePrefix && is300Weight && isNeutralIntent,
    'outline-neutral-400': isOutlinePrefix && is400Weight && isNeutralIntent,
    'outline-neutral-500': isOutlinePrefix && is500Weight && isNeutralIntent,
    'outline-neutral-600': isOutlinePrefix && is600Weight && isNeutralIntent,
    'outline-neutral-700': isOutlinePrefix && is700Weight && isNeutralIntent,
    'outline-neutral-800': isOutlinePrefix && is800Weight && isNeutralIntent,
    'outline-neutral-900': isOutlinePrefix && is900Weight && isNeutralIntent,
    // primary
    'outline-primary-50': isOutlinePrefix && is50Weight && isPrimaryIntent,
    'outline-primary-100': isOutlinePrefix && is100Weight && isPrimaryIntent,
    'outline-primary-200': isOutlinePrefix && is200Weight && isPrimaryIntent,
    'outline-primary-300': isOutlinePrefix && is300Weight && isPrimaryIntent,
    'outline-primary-400': isOutlinePrefix && is400Weight && isPrimaryIntent,
    'outline-primary-500': isOutlinePrefix && is500Weight && isPrimaryIntent,
    'outline-primary-600': isOutlinePrefix && is600Weight && isPrimaryIntent,
    'outline-primary-700': isOutlinePrefix && is700Weight && isPrimaryIntent,
    'outline-primary-800': isOutlinePrefix && is800Weight && isPrimaryIntent,
    'outline-primary-900': isOutlinePrefix && is900Weight && isPrimaryIntent,
    // info
    'outline-info-50': isOutlinePrefix && is50Weight && isInfoIntent,
    'outline-info-100': isOutlinePrefix && is100Weight && isInfoIntent,
    'outline-info-200': isOutlinePrefix && is200Weight && isInfoIntent,
    'outline-info-300': isOutlinePrefix && is300Weight && isInfoIntent,
    'outline-info-400': isOutlinePrefix && is400Weight && isInfoIntent,
    'outline-info-500': isOutlinePrefix && is500Weight && isInfoIntent,
    'outline-info-600': isOutlinePrefix && is600Weight && isInfoIntent,
    'outline-info-700': isOutlinePrefix && is700Weight && isInfoIntent,
    'outline-info-800': isOutlinePrefix && is800Weight && isInfoIntent,
    'outline-info-900': isOutlinePrefix && is900Weight && isInfoIntent,
    // success
    'outline-success-50': isOutlinePrefix && is50Weight && isSuccessIntent,
    'outline-success-100': isOutlinePrefix && is100Weight && isSuccessIntent,
    'outline-success-200': isOutlinePrefix && is200Weight && isSuccessIntent,
    'outline-success-300': isOutlinePrefix && is300Weight && isSuccessIntent,
    'outline-success-400': isOutlinePrefix && is400Weight && isSuccessIntent,
    'outline-success-500': isOutlinePrefix && is500Weight && isSuccessIntent,
    'outline-success-600': isOutlinePrefix && is600Weight && isSuccessIntent,
    'outline-success-700': isOutlinePrefix && is700Weight && isSuccessIntent,
    'outline-success-800': isOutlinePrefix && is800Weight && isSuccessIntent,
    'outline-success-900': isOutlinePrefix && is900Weight && isSuccessIntent,
    // warning
    'outline-warning-50': isOutlinePrefix && is50Weight && isWarningIntent,
    'outline-warning-100': isOutlinePrefix && is100Weight && isWarningIntent,
    'outline-warning-200': isOutlinePrefix && is200Weight && isWarningIntent,
    'outline-warning-300': isOutlinePrefix && is300Weight && isWarningIntent,
    'outline-warning-400': isOutlinePrefix && is400Weight && isWarningIntent,
    'outline-warning-500': isOutlinePrefix && is500Weight && isWarningIntent,
    'outline-warning-600': isOutlinePrefix && is600Weight && isWarningIntent,
    'outline-warning-700': isOutlinePrefix && is700Weight && isWarningIntent,
    'outline-warning-800': isOutlinePrefix && is800Weight && isWarningIntent,
    'outline-warning-900': isOutlinePrefix && is900Weight && isWarningIntent,
    // danger
    'outline-danger-50': isOutlinePrefix && is50Weight && isDangerIntent,
    'outline-danger-100': isOutlinePrefix && is100Weight && isDangerIntent,
    'outline-danger-200': isOutlinePrefix && is200Weight && isDangerIntent,
    'outline-danger-300': isOutlinePrefix && is300Weight && isDangerIntent,
    'outline-danger-400': isOutlinePrefix && is400Weight && isDangerIntent,
    'outline-danger-500': isOutlinePrefix && is500Weight && isDangerIntent,
    'outline-danger-600': isOutlinePrefix && is600Weight && isDangerIntent,
    'outline-danger-700': isOutlinePrefix && is700Weight && isDangerIntent,
    'outline-danger-800': isOutlinePrefix && is800Weight && isDangerIntent,
    'outline-danger-900': isOutlinePrefix && is900Weight && isDangerIntent,
    /**
     * @name ring
     */
    // light
    'ring-light-50': isRingPrefix && is50Weight && isLightIntent,
    'ring-light-100': isRingPrefix && is100Weight && isLightIntent,
    'ring-light-200': isRingPrefix && is200Weight && isLightIntent,
    'ring-light-300': isRingPrefix && is300Weight && isLightIntent,
    'ring-light-400': isRingPrefix && is400Weight && isLightIntent,
    'ring-light-500': isRingPrefix && is500Weight && isLightIntent,
    'ring-light-600': isRingPrefix && is600Weight && isLightIntent,
    'ring-light-700': isRingPrefix && is700Weight && isLightIntent,
    'ring-light-800': isRingPrefix && is800Weight && isLightIntent,
    'ring-light-900': isRingPrefix && is900Weight && isLightIntent,
    // dark
    'ring-dark-50': isRingPrefix && is50Weight && isDarkIntent,
    'ring-dark-100': isRingPrefix && is100Weight && isDarkIntent,
    'ring-dark-200': isRingPrefix && is200Weight && isDarkIntent,
    'ring-dark-300': isRingPrefix && is300Weight && isDarkIntent,
    'ring-dark-400': isRingPrefix && is400Weight && isDarkIntent,
    'ring-dark-500': isRingPrefix && is500Weight && isDarkIntent,
    'ring-dark-600': isRingPrefix && is600Weight && isDarkIntent,
    'ring-dark-700': isRingPrefix && is700Weight && isDarkIntent,
    'ring-dark-800': isRingPrefix && is800Weight && isDarkIntent,
    'ring-dark-900': isRingPrefix && is900Weight && isDarkIntent,
    // neutral
    'ring-neutral-50': isRingPrefix && is50Weight && isNeutralIntent,
    'ring-neutral-100': isRingPrefix && is100Weight && isNeutralIntent,
    'ring-neutral-200': isRingPrefix && is200Weight && isNeutralIntent,
    'ring-neutral-300': isRingPrefix && is300Weight && isNeutralIntent,
    'ring-neutral-400': isRingPrefix && is400Weight && isNeutralIntent,
    'ring-neutral-500': isRingPrefix && is500Weight && isNeutralIntent,
    'ring-neutral-600': isRingPrefix && is600Weight && isNeutralIntent,
    'ring-neutral-700': isRingPrefix && is700Weight && isNeutralIntent,
    'ring-neutral-800': isRingPrefix && is800Weight && isNeutralIntent,
    'ring-neutral-900': isRingPrefix && is900Weight && isNeutralIntent,
    // primary
    'ring-primary-50': isRingPrefix && is50Weight && isPrimaryIntent,
    'ring-primary-100': isRingPrefix && is100Weight && isPrimaryIntent,
    'ring-primary-200': isRingPrefix && is200Weight && isPrimaryIntent,
    'ring-primary-300': isRingPrefix && is300Weight && isPrimaryIntent,
    'ring-primary-400': isRingPrefix && is400Weight && isPrimaryIntent,
    'ring-primary-500': isRingPrefix && is500Weight && isPrimaryIntent,
    'ring-primary-600': isRingPrefix && is600Weight && isPrimaryIntent,
    'ring-primary-700': isRingPrefix && is700Weight && isPrimaryIntent,
    'ring-primary-800': isRingPrefix && is800Weight && isPrimaryIntent,
    'ring-primary-900': isRingPrefix && is900Weight && isPrimaryIntent,
    // info
    'ring-info-50': isRingPrefix && is50Weight && isInfoIntent,
    'ring-info-100': isRingPrefix && is100Weight && isInfoIntent,
    'ring-info-200': isRingPrefix && is200Weight && isInfoIntent,
    'ring-info-300': isRingPrefix && is300Weight && isInfoIntent,
    'ring-info-400': isRingPrefix && is400Weight && isInfoIntent,
    'ring-info-500': isRingPrefix && is500Weight && isInfoIntent,
    'ring-info-600': isRingPrefix && is600Weight && isInfoIntent,
    'ring-info-700': isRingPrefix && is700Weight && isInfoIntent,
    'ring-info-800': isRingPrefix && is800Weight && isInfoIntent,
    'ring-info-900': isRingPrefix && is900Weight && isInfoIntent,
    // success
    'ring-success-50': isRingPrefix && is50Weight && isSuccessIntent,
    'ring-success-100': isRingPrefix && is100Weight && isSuccessIntent,
    'ring-success-200': isRingPrefix && is200Weight && isSuccessIntent,
    'ring-success-300': isRingPrefix && is300Weight && isSuccessIntent,
    'ring-success-400': isRingPrefix && is400Weight && isSuccessIntent,
    'ring-success-500': isRingPrefix && is500Weight && isSuccessIntent,
    'ring-success-600': isRingPrefix && is600Weight && isSuccessIntent,
    'ring-success-700': isRingPrefix && is700Weight && isSuccessIntent,
    'ring-success-800': isRingPrefix && is800Weight && isSuccessIntent,
    'ring-success-900': isRingPrefix && is900Weight && isSuccessIntent,
    // warning
    'ring-warning-50': isRingPrefix && is50Weight && isWarningIntent,
    'ring-warning-100': isRingPrefix && is100Weight && isWarningIntent,
    'ring-warning-200': isRingPrefix && is200Weight && isWarningIntent,
    'ring-warning-300': isRingPrefix && is300Weight && isWarningIntent,
    'ring-warning-400': isRingPrefix && is400Weight && isWarningIntent,
    'ring-warning-500': isRingPrefix && is500Weight && isWarningIntent,
    'ring-warning-600': isRingPrefix && is600Weight && isWarningIntent,
    'ring-warning-700': isRingPrefix && is700Weight && isWarningIntent,
    'ring-warning-800': isRingPrefix && is800Weight && isWarningIntent,
    'ring-warning-900': isRingPrefix && is900Weight && isWarningIntent,
    // danger
    'ring-danger-50': isRingPrefix && is50Weight && isDangerIntent,
    'ring-danger-100': isRingPrefix && is100Weight && isDangerIntent,
    'ring-danger-200': isRingPrefix && is200Weight && isDangerIntent,
    'ring-danger-300': isRingPrefix && is300Weight && isDangerIntent,
    'ring-danger-400': isRingPrefix && is400Weight && isDangerIntent,
    'ring-danger-500': isRingPrefix && is500Weight && isDangerIntent,
    'ring-danger-600': isRingPrefix && is600Weight && isDangerIntent,
    'ring-danger-700': isRingPrefix && is700Weight && isDangerIntent,
    'ring-danger-800': isRingPrefix && is800Weight && isDangerIntent,
    'ring-danger-900': isRingPrefix && is900Weight && isDangerIntent,
    /**
     * @name ring-offset
     */
    // light
    'ring-offset-light-50': isRingOffsetPrefix && is50Weight && isLightIntent,
    'ring-offset-light-100': isRingOffsetPrefix && is100Weight && isLightIntent,
    'ring-offset-light-200': isRingOffsetPrefix && is200Weight && isLightIntent,
    'ring-offset-light-300': isRingOffsetPrefix && is300Weight && isLightIntent,
    'ring-offset-light-400': isRingOffsetPrefix && is400Weight && isLightIntent,
    'ring-offset-light-500': isRingOffsetPrefix && is500Weight && isLightIntent,
    'ring-offset-light-600': isRingOffsetPrefix && is600Weight && isLightIntent,
    'ring-offset-light-700': isRingOffsetPrefix && is700Weight && isLightIntent,
    'ring-offset-light-800': isRingOffsetPrefix && is800Weight && isLightIntent,
    'ring-offset-light-900': isRingOffsetPrefix && is900Weight && isLightIntent,
    // dark
    'ring-offset-dark-50': isRingOffsetPrefix && is50Weight && isDarkIntent,
    'ring-offset-dark-100': isRingOffsetPrefix && is100Weight && isDarkIntent,
    'ring-offset-dark-200': isRingOffsetPrefix && is200Weight && isDarkIntent,
    'ring-offset-dark-300': isRingOffsetPrefix && is300Weight && isDarkIntent,
    'ring-offset-dark-400': isRingOffsetPrefix && is400Weight && isDarkIntent,
    'ring-offset-dark-500': isRingOffsetPrefix && is500Weight && isDarkIntent,
    'ring-offset-dark-600': isRingOffsetPrefix && is600Weight && isDarkIntent,
    'ring-offset-dark-700': isRingOffsetPrefix && is700Weight && isDarkIntent,
    'ring-offset-dark-800': isRingOffsetPrefix && is800Weight && isDarkIntent,
    'ring-offset-dark-900': isRingOffsetPrefix && is900Weight && isDarkIntent,
    // neutral
    'ring-offset-neutral-50': isRingOffsetPrefix && is50Weight && isNeutralIntent,
    'ring-offset-neutral-100': isRingOffsetPrefix && is100Weight && isNeutralIntent,
    'ring-offset-neutral-200': isRingOffsetPrefix && is200Weight && isNeutralIntent,
    'ring-offset-neutral-300': isRingOffsetPrefix && is300Weight && isNeutralIntent,
    'ring-offset-neutral-400': isRingOffsetPrefix && is400Weight && isNeutralIntent,
    'ring-offset-neutral-500': isRingOffsetPrefix && is500Weight && isNeutralIntent,
    'ring-offset-neutral-600': isRingOffsetPrefix && is600Weight && isNeutralIntent,
    'ring-offset-neutral-700': isRingOffsetPrefix && is700Weight && isNeutralIntent,
    'ring-offset-neutral-800': isRingOffsetPrefix && is800Weight && isNeutralIntent,
    'ring-offset-neutral-900': isRingOffsetPrefix && is900Weight && isNeutralIntent,
    // primary
    'ring-offset-primary-50': isRingOffsetPrefix && is50Weight && isPrimaryIntent,
    'ring-offset-primary-100': isRingOffsetPrefix && is100Weight && isPrimaryIntent,
    'ring-offset-primary-200': isRingOffsetPrefix && is200Weight && isPrimaryIntent,
    'ring-offset-primary-300': isRingOffsetPrefix && is300Weight && isPrimaryIntent,
    'ring-offset-primary-400': isRingOffsetPrefix && is400Weight && isPrimaryIntent,
    'ring-offset-primary-500': isRingOffsetPrefix && is500Weight && isPrimaryIntent,
    'ring-offset-primary-600': isRingOffsetPrefix && is600Weight && isPrimaryIntent,
    'ring-offset-primary-700': isRingOffsetPrefix && is700Weight && isPrimaryIntent,
    'ring-offset-primary-800': isRingOffsetPrefix && is800Weight && isPrimaryIntent,
    'ring-offset-primary-900': isRingOffsetPrefix && is900Weight && isPrimaryIntent,
    // info
    'ring-offset-info-50': isRingOffsetPrefix && is50Weight && isInfoIntent,
    'ring-offset-info-100': isRingOffsetPrefix && is100Weight && isInfoIntent,
    'ring-offset-info-200': isRingOffsetPrefix && is200Weight && isInfoIntent,
    'ring-offset-info-300': isRingOffsetPrefix && is300Weight && isInfoIntent,
    'ring-offset-info-400': isRingOffsetPrefix && is400Weight && isInfoIntent,
    'ring-offset-info-500': isRingOffsetPrefix && is500Weight && isInfoIntent,
    'ring-offset-info-600': isRingOffsetPrefix && is600Weight && isInfoIntent,
    'ring-offset-info-700': isRingOffsetPrefix && is700Weight && isInfoIntent,
    'ring-offset-info-800': isRingOffsetPrefix && is800Weight && isInfoIntent,
    'ring-offset-info-900': isRingOffsetPrefix && is900Weight && isInfoIntent,
    // success
    'ring-offset-success-50': isRingOffsetPrefix && is50Weight && isSuccessIntent,
    'ring-offset-success-100': isRingOffsetPrefix && is100Weight && isSuccessIntent,
    'ring-offset-success-200': isRingOffsetPrefix && is200Weight && isSuccessIntent,
    'ring-offset-success-300': isRingOffsetPrefix && is300Weight && isSuccessIntent,
    'ring-offset-success-400': isRingOffsetPrefix && is400Weight && isSuccessIntent,
    'ring-offset-success-500': isRingOffsetPrefix && is500Weight && isSuccessIntent,
    'ring-offset-success-600': isRingOffsetPrefix && is600Weight && isSuccessIntent,
    'ring-offset-success-700': isRingOffsetPrefix && is700Weight && isSuccessIntent,
    'ring-offset-success-800': isRingOffsetPrefix && is800Weight && isSuccessIntent,
    'ring-offset-success-900': isRingOffsetPrefix && is900Weight && isSuccessIntent,
    // warning
    'ring-offset-warning-50': isRingOffsetPrefix && is50Weight && isWarningIntent,
    'ring-offset-warning-100': isRingOffsetPrefix && is100Weight && isWarningIntent,
    'ring-offset-warning-200': isRingOffsetPrefix && is200Weight && isWarningIntent,
    'ring-offset-warning-300': isRingOffsetPrefix && is300Weight && isWarningIntent,
    'ring-offset-warning-400': isRingOffsetPrefix && is400Weight && isWarningIntent,
    'ring-offset-warning-500': isRingOffsetPrefix && is500Weight && isWarningIntent,
    'ring-offset-warning-600': isRingOffsetPrefix && is600Weight && isWarningIntent,
    'ring-offset-warning-700': isRingOffsetPrefix && is700Weight && isWarningIntent,
    'ring-offset-warning-800': isRingOffsetPrefix && is800Weight && isWarningIntent,
    'ring-offset-warning-900': isRingOffsetPrefix && is900Weight && isWarningIntent,
    // danger
    'ring-offset-danger-50': isRingOffsetPrefix && is50Weight && isDangerIntent,
    'ring-offset-danger-100': isRingOffsetPrefix && is100Weight && isDangerIntent,
    'ring-offset-danger-200': isRingOffsetPrefix && is200Weight && isDangerIntent,
    'ring-offset-danger-300': isRingOffsetPrefix && is300Weight && isDangerIntent,
    'ring-offset-danger-400': isRingOffsetPrefix && is400Weight && isDangerIntent,
    'ring-offset-danger-500': isRingOffsetPrefix && is500Weight && isDangerIntent,
    'ring-offset-danger-600': isRingOffsetPrefix && is600Weight && isDangerIntent,
    'ring-offset-danger-700': isRingOffsetPrefix && is700Weight && isDangerIntent,
    'ring-offset-danger-800': isRingOffsetPrefix && is800Weight && isDangerIntent,
    'ring-offset-danger-900': isRingOffsetPrefix && is900Weight && isDangerIntent,
    /**
     * @name fill
     */
    // light
    'fill-light-50': isFillPrefix && is50Weight && isLightIntent,
    'fill-light-100': isFillPrefix && is100Weight && isLightIntent,
    'fill-light-200': isFillPrefix && is200Weight && isLightIntent,
    'fill-light-300': isFillPrefix && is300Weight && isLightIntent,
    'fill-light-400': isFillPrefix && is400Weight && isLightIntent,
    'fill-light-500': isFillPrefix && is500Weight && isLightIntent,
    'fill-light-600': isFillPrefix && is600Weight && isLightIntent,
    'fill-light-700': isFillPrefix && is700Weight && isLightIntent,
    'fill-light-800': isFillPrefix && is800Weight && isLightIntent,
    'fill-light-900': isFillPrefix && is900Weight && isLightIntent,
    // dark
    'fill-dark-50': isFillPrefix && is50Weight && isDarkIntent,
    'fill-dark-100': isFillPrefix && is100Weight && isDarkIntent,
    'fill-dark-200': isFillPrefix && is200Weight && isDarkIntent,
    'fill-dark-300': isFillPrefix && is300Weight && isDarkIntent,
    'fill-dark-400': isFillPrefix && is400Weight && isDarkIntent,
    'fill-dark-500': isFillPrefix && is500Weight && isDarkIntent,
    'fill-dark-600': isFillPrefix && is600Weight && isDarkIntent,
    'fill-dark-700': isFillPrefix && is700Weight && isDarkIntent,
    'fill-dark-800': isFillPrefix && is800Weight && isDarkIntent,
    'fill-dark-900': isFillPrefix && is900Weight && isDarkIntent,
    // neutral
    'fill-neutral-50': isFillPrefix && is50Weight && isNeutralIntent,
    'fill-neutral-100': isFillPrefix && is100Weight && isNeutralIntent,
    'fill-neutral-200': isFillPrefix && is200Weight && isNeutralIntent,
    'fill-neutral-300': isFillPrefix && is300Weight && isNeutralIntent,
    'fill-neutral-400': isFillPrefix && is400Weight && isNeutralIntent,
    'fill-neutral-500': isFillPrefix && is500Weight && isNeutralIntent,
    'fill-neutral-600': isFillPrefix && is600Weight && isNeutralIntent,
    'fill-neutral-700': isFillPrefix && is700Weight && isNeutralIntent,
    'fill-neutral-800': isFillPrefix && is800Weight && isNeutralIntent,
    'fill-neutral-900': isFillPrefix && is900Weight && isNeutralIntent,
    // primary
    'fill-primary-50': isFillPrefix && is50Weight && isPrimaryIntent,
    'fill-primary-100': isFillPrefix && is100Weight && isPrimaryIntent,
    'fill-primary-200': isFillPrefix && is200Weight && isPrimaryIntent,
    'fill-primary-300': isFillPrefix && is300Weight && isPrimaryIntent,
    'fill-primary-400': isFillPrefix && is400Weight && isPrimaryIntent,
    'fill-primary-500': isFillPrefix && is500Weight && isPrimaryIntent,
    'fill-primary-600': isFillPrefix && is600Weight && isPrimaryIntent,
    'fill-primary-700': isFillPrefix && is700Weight && isPrimaryIntent,
    'fill-primary-800': isFillPrefix && is800Weight && isPrimaryIntent,
    'fill-primary-900': isFillPrefix && is900Weight && isPrimaryIntent,
    // info
    'fill-info-50': isFillPrefix && is50Weight && isInfoIntent,
    'fill-info-100': isFillPrefix && is100Weight && isInfoIntent,
    'fill-info-200': isFillPrefix && is200Weight && isInfoIntent,
    'fill-info-300': isFillPrefix && is300Weight && isInfoIntent,
    'fill-info-400': isFillPrefix && is400Weight && isInfoIntent,
    'fill-info-500': isFillPrefix && is500Weight && isInfoIntent,
    'fill-info-600': isFillPrefix && is600Weight && isInfoIntent,
    'fill-info-700': isFillPrefix && is700Weight && isInfoIntent,
    'fill-info-800': isFillPrefix && is800Weight && isInfoIntent,
    'fill-info-900': isFillPrefix && is900Weight && isInfoIntent,
    // success
    'fill-success-50': isFillPrefix && is50Weight && isSuccessIntent,
    'fill-success-100': isFillPrefix && is100Weight && isSuccessIntent,
    'fill-success-200': isFillPrefix && is200Weight && isSuccessIntent,
    'fill-success-300': isFillPrefix && is300Weight && isSuccessIntent,
    'fill-success-400': isFillPrefix && is400Weight && isSuccessIntent,
    'fill-success-500': isFillPrefix && is500Weight && isSuccessIntent,
    'fill-success-600': isFillPrefix && is600Weight && isSuccessIntent,
    'fill-success-700': isFillPrefix && is700Weight && isSuccessIntent,
    'fill-success-800': isFillPrefix && is800Weight && isSuccessIntent,
    'fill-success-900': isFillPrefix && is900Weight && isSuccessIntent,
    // warning
    'fill-warning-50': isFillPrefix && is50Weight && isWarningIntent,
    'fill-warning-100': isFillPrefix && is100Weight && isWarningIntent,
    'fill-warning-200': isFillPrefix && is200Weight && isWarningIntent,
    'fill-warning-300': isFillPrefix && is300Weight && isWarningIntent,
    'fill-warning-400': isFillPrefix && is400Weight && isWarningIntent,
    'fill-warning-500': isFillPrefix && is500Weight && isWarningIntent,
    'fill-warning-600': isFillPrefix && is600Weight && isWarningIntent,
    'fill-warning-700': isFillPrefix && is700Weight && isWarningIntent,
    'fill-warning-800': isFillPrefix && is800Weight && isWarningIntent,
    'fill-warning-900': isFillPrefix && is900Weight && isWarningIntent,
    // danger
    'fill-danger-50': isFillPrefix && is50Weight && isDangerIntent,
    'fill-danger-100': isFillPrefix && is100Weight && isDangerIntent,
    'fill-danger-200': isFillPrefix && is200Weight && isDangerIntent,
    'fill-danger-300': isFillPrefix && is300Weight && isDangerIntent,
    'fill-danger-400': isFillPrefix && is400Weight && isDangerIntent,
    'fill-danger-500': isFillPrefix && is500Weight && isDangerIntent,
    'fill-danger-600': isFillPrefix && is600Weight && isDangerIntent,
    'fill-danger-700': isFillPrefix && is700Weight && isDangerIntent,
    'fill-danger-800': isFillPrefix && is800Weight && isDangerIntent,
    'fill-danger-900': isFillPrefix && is900Weight && isDangerIntent,
  });
}
