# @see https://docs.github.com/en/discussions/managing-discussions-for-your-community/syntax-for-discussion-category-forms
title: "[Idea] "
labels: ["idea"]
body:
  - type: textarea
    id: background
    attributes:
      label: Background
      description: "What is the idea and why is it important?"
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Goals
      description: "What are the goals of this idea?"
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation
      description: "What are the steps to implement this idea?"
      value: |
        1.
        2.
        3.
    validations:
      required: true
