# see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
name: Publish Package at Github Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main, develop, /^release\/.*$/, /^feature\/.*$/, /^bugfix\/.*$/, /^hotfix\/.*$/, /^support\/.*$/]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**/*.md'

jobs:
  cd:
    runs-on: ubuntu-latest
    name: Continuous Deployment
    env:
      GITHUB_TOKEN: ${{secrets.SEOLHUN_GITHUB_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js & pnpm
        uses: ./.github/actions/node-pnpm-setup

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: "chore: Bum up packages version to publish"
          commit: "chore: Bump up packages version to publish"
          version: pnpm changeset:version
          publish: pnpm changeset:publish
        env:
          GITHUB_TOKEN: ${{secrets.SEOLHUN_GITHUB_TOKEN}}
