name: Stage Build

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: npm ci
        env:
          SEOLHUN_GITHUB_TOKEN: ${{secrets.SEOLHUN_GITHUB_TOKEN}}

      - name: Lint
        if: ${{ always() }}
        run: npm run lint

      - name: Test
        if: ${{ always() }}
        run: npm run test

      - name: Build Storybook
        run: npm run build:storybook

      - name: Build
        run: npm run build
